### ISSUE TITLE
UX for selecting work item type in the board view

### ISSUE THREAD

**Issue by sanbornsen** [fabric8io/fabric8-planner#1053]
In the board view, we need a work item type selector, based on which the state columns will update in the page.

Related to - #671

**Comment by sanbornsen** [comment]
UX - https://redhat.invisionapp.com/share/56AH8F1XM#/screens/221408835

**Comment by catrobson** [comment]
Thanks for capturing the need to add the type selector on the board view!  Please reach out to me if you have any questions during implementation, I'm subscribed to this thread as well.
