### ISSUE TITLE
Need to refactor UI functional test code to be consistent

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1055]
We need to refactor UI functional test code to be consistent in how we define and manipulate UI elements.

Defining the functions that return the UI elements as "get" operations results in the code being easier to read and maintain:

```
  /* Icon for the user assigned to the workitem */
  get workItemDetailAssigneeIcon () {
    return element(by.css(".user-assign-icon"));
  }
  clickworkItemDetailAssigneeIcon () { 
    return this.workItemDetailAssigneeIcon.click();
  }
```

* Code that accesses the UI elements consists of **references to the objects that represent the UI elements** - for example:

`browser.wait(until.elementToBeClickable(detailPage.workItemDetailAssigneeIcon), constants.WAIT, 'Failed to find Assignee Icon'); `

* Code to perform actions on the UI elements consists of the **invocation of functions** - for example:

` detailPage.clickworkItemDetailAssigneeIcon();`

**Comment by naina-verma** [comment]
https://github.com/fabric8io/fabric8-planner/pull/1051 Merged !

**Comment by ldimaggi** [comment]
This issue actually relates to all the test code, not just the assignment related test referenced in the issue's description.   ;-)

We should review the code and then update it all - to be consistent. Thx!
