### ISSUE TITLE
Building Planner UI from master - spaces dropdown box is not working

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1073]
This issue just showed up - late on March 3 - see screenshot:

![screenshot from 2017-03-03 17-17-47](https://cloud.githubusercontent.com/assets/642621/23571157/a32ffc3a-0035-11e7-91cc-ec9b141e20ae.png)

**Comment by pmuir** [comment]
I fixed this earlier today I believe - please check HEAD.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
