### ISSUE TITLE
Unable to delete Work Item 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1106]
Unable to delete Work Item 
- No Confirm dialog shows up after clicking on the Delete menu from Kebab

**Comment by naina-verma** [comment]
@sanbornsen please look into it

**Comment by naina-verma** [comment]
https://github.com/fabric8io/fabric8-planner/pull/1111

**Comment by vikram-raj** [comment]
Is #1103 is the same issue?

**Comment by naina-verma** [comment]
yes !
