### ISSUE TITLE
Markup/HTML toggle button becomes counter-intuitive

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1138]
In editing a workitem's description field, the user is given the option of selecting Markup or HTML.

* When the workitem is opened for editing, an HTML representation of the text is displayed and the button reads "View Markdown."
* Clicking on the button causes the display of the button to change to "View HTML" - but the display of the text is not changed. 
* Clicking on button again causes the display of the button to "View Markdown" - and the display of the text is changed to markdown/rendered text.
* At this point, the title of the button = the chacteristics of the displayed text and not the opposite.

As a result
* In order to view the HTML, the user must click on a button that already reads "View HTML".
* In order to view the markdown, the user must click on a button that already reads "View Markdown"

![1](https://cloud.githubusercontent.com/assets/642621/23760454/bb2a0f6a-04bd-11e7-9f35-ce09d123984e.png)

![2](https://cloud.githubusercontent.com/assets/642621/23760453/bb29dcc0-04bd-11e7-90aa-1f5771b16eef.png)

![3](https://cloud.githubusercontent.com/assets/642621/23760452/bb25e0fc-04bd-11e7-847e-6b5c8b7a9a9c.png)

**Comment by mindreeper2420** [comment]
Hey Len - this wasn't specced out in the wireframe, as the view html/view markdown was not part of the initial run. If this is a feature needed for the release, I can add on to my wireframe for showing markdown in the description field.
