### ISSUE TITLE
Planner built from master on March 9 - workitems associated with an iteration are not displayed with the iteration

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1140]
See the attached screenshot. I expected to see the workitems listed below the iteration.

![screenshot from 2017-03-09 22-30-35](https://cloud.githubusercontent.com/assets/642621/23781075/d33d796a-0518-11e7-812b-9640458044d7.png)

**Comment by Mgranfie** [comment]
The work items for the iteration, that is selected in the left pane, are
then listed to the right in the list...

The progress bar for the iterations is not displaying here?

**Comment by ldimaggi** [comment]
Ah - OK Monica - thanks!
