### ISSUE TITLE
Area search doesn't display appropriate results on top 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1164]
Area search doesn't display appropriate results on top 
Steps to reproduce 
- search area 
- if your search string is present in area's list but it is down in the list , In that case you have to scroll down and select , which is not appropriate for end user
Expected : the matching search result should come up during search 
Video Link https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COTWFXeW1ZejhZYTA/view?usp=sharing

**Comment by nimishamukherjee** [comment]
@naina-verma please verify this issue.

**Comment by nimishamukherjee** [comment]
Fixed on planner. Need to update on platform.

**Comment by naina-verma** [comment]
Verified
