### ISSUE TITLE
Expand iteration functional UI tests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1202]
Cover associating workitems with iterations
Cover iterations tracking workitems’ transitions from New to Closed

**Comment by naina-verma** [comment]
Hi @ldimaggi ,
am working on it , will submit the PR EOD

**Comment by naina-verma** [comment]
https://github.com/naina-verma/fabric8-planner/tree/test-associateWIT

**Comment by ldimaggi** [comment]
https://github.com/fabric8io/fabric8-planner/pull/1220
