### ISSUE TITLE
If a user inadvertently cancels out of entering a new workitem's title - the title field is removed 

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1212]
Steps to recreate this bug:

1) Create a new workitem through the detail page:

![screenshot from 2017-03-16 12-40-15](https://cloud.githubusercontent.com/assets/642621/24007890/56d72a1e-0a46-11e7-9fd6-9ada95913b2b.png)

2) Instead of entering a title for the workitem, click on the "x" button:

![screenshot from 2017-03-16 12-40-40](https://cloud.githubusercontent.com/assets/642621/24007903/62d39a8c-0a46-11e7-9088-091c6f28c021.png)

3) At this point, the user has no way of getting the title field to reappear - the creation of the workitem must be stopped and started over.

**Comment by nimishamukherjee** [comment]
@vikram-raj can you check PR #1294 . This fixes big #740.

**Comment by vikram-raj** [comment]
fixed in PR #1294
