### ISSUE TITLE
Workitem - detail pane - iteration selection - cancel button fails - raises exception

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1213]
The button is not working as it calls the wrong function. It calls closeRestFields instead of closeUserRestFields

**Comment by naina-verma** [comment]
@ldimaggi can you please verify this ! 
As the steps to reproduce are not clear to me i can't mark it as verified !

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
