### ISSUE TITLE
http://www.prod-preview.openshift.io/index.html - "Register for Developer Preview" button display is truncated

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1223]
![screenshot from 2017-03-19 17-58-07](https://cloud.githubusercontent.com/assets/642621/24085229/6853cb8c-0cce-11e7-8bf7-9b93b8679f4c.png)

**Comment by mindreeper2420** [comment]
Hi @ldimaggi - can you file this bug on https://github.com/openshiftio/www.openshift.io? The Fabric8-Planner team is not working on this page.

Note - I'll have a PR to fix this asap. The UXD team is designing and developing this page.

**Comment by mindreeper2420** [comment]
this has been fixed in the latest prod-preview. to see the correct version, clear cache, hard reset and correct styles will appear.
