### ISSUE TITLE
UI layouts for scroll on link item,title looks different from invision 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1225]
UI layouts for title , link total etc looks different from invision 

![screenshot from 2017-03-20 11-02-29](https://cloud.githubusercontent.com/assets/19172870/24089467/07199254-0d5d-11e7-98dc-63b938d54ba1.png)
![screenshot from 2017-03-20 11-03-16](https://cloud.githubusercontent.com/assets/19172870/24089468/0719b928-0d5d-11e7-9c0e-a8c1a7f40a01.png)

**Comment by mindreeper2420** [comment]
@naina-verma which InVision link are you referring to?

**Comment by mindreeper2420** [comment]
@naina-verma this is the design that I updated the Detail Panel off of: https://redhat.invisionapp.com/share/D4ARY0Z6Z#/223026367_A-0100_Updated. It will be added to our list of designs this week.

**Comment by naina-verma** [comment]
Hi @mindreeper2420,
I have discussed with @nimishamukherjee that it is intentional changes !
