### ISSUE TITLE
Make big plus symbol on empty WI list clickable

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#1246]
I would love to see that this big plus symbol that is JUMPING IN MY FACE is clickable. But currently it isn't.

![screenshot from 2017-03-22 14-17-04](https://cloud.githubusercontent.com/assets/193408/24202158/9392050c-0f12-11e7-8ff8-6d37422343c2.png)

@Mgranfie this would increase the usability, no?

**Comment by mindreeper2420** [comment]
@kwk can you see if it is just as bad when Epics are empty? We are using the same empty state message for that as well. I don't notice those things, since I did them :)

**Comment by kwk** [comment]
> @kwk can you see if it is just as bad when Epics are empty?

I don't get what you're saying.

**Comment by Mgranfie** [comment]
This is good feedback Konrad... will look into this!

**Comment by mindreeper2420** [comment]
@kwk ignore my comment - doesn't apply 😄

**Comment by maxandersen** [comment]
+1 on this one - its the biggest target on the screen but it doesn't do anything. +1 on making it actually "Add" or remove it.

**Comment by debloper** [comment]
Fixed with #1685
