### ISSUE TITLE
Quick add does not work

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1268]
The ability to quick add a work item using the bottom bar is currently not resulting in a work item being created and added to the top of the backlog.

Clicking the "Create work item" link results in no fields.

**Comment by SMahil** [comment]
@mindreeper2420 This works fine on prod. Can you verify it?

**Comment by mindreeper2420** [comment]
Quick Add works on prod-preview now, but the full add does not. I'll file a new bug for that.

**Comment by mindreeper2420** [comment]
Verified that both methods for adding an item work on prod-preview.
