### ISSUE TITLE
Show WI Selection on board view

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1271]
Reproduction:
- Open a work item in the board view
- WI card in the board view is not shown as selected state

**Comment by SMahil** [comment]
@fabric8io/uxd please provide the visual spec for the same

**Comment by mindreeper2420** [comment]
@SMahil https://redhat.invisionapp.com/share/AWB5N9NGC#/210504573_Boardview-Click1

**Comment by debloper** [comment]
Presently it behaves as intended. Please re-verify.
