### ISSUE TITLE
Left hand view pane selection & filtering

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1272]
In the left hand panel on backlog view and boards view selection is not working properly, nor the filtering of work items.

Viewable issues:
- Backlog should be selected by default when coming into the page
- Work items should be filtered to only the selection shown - Iteration should only show WIs assigned to that iteration.  Backlog should show work items that are not Done or Closed.
- Meta information as designed is not showing under the iterations

**Comment by debloper** [comment]
I think this is resolved now, please re-verify.

**Comment by catrobson** [comment]
+1, resolved.  Closing issue.
