### ISSUE TITLE
On http://prod-preview.openshift.io/ - in backlog view, users are presented with a checkbox for each wiorkitem, but they have no affect

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1274]
And - users are only able to select one workitem at a time by clicking the checkbox.

![screenshot from 2017-03-23 11-40-48](https://cloud.githubusercontent.com/assets/642621/24263664/3299a864-0fd4-11e7-865a-9033c689ed64.png)

**Comment by vikram-raj** [comment]
@ldimaggi We are not allowing the user to select multiple work items. The user can move only one work item at a time.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
