### ISSUE TITLE
On http://prod-preview.openshift.io - quick create for workitems only allows for planner type workitems

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1275]
A dropdown box for workitem type is displayed for the user, but only the planner type is included.

![screenshot from 2017-03-23 11-38-50](https://cloud.githubusercontent.com/assets/642621/24263737/6dc7e5ae-0fd4-11e7-9c09-1cfa3429176d.png)

**Comment by mindreeper2420** [comment]
a UX note on this - it should not be a button, just the icon

**Comment by michaelkleinhenz** [comment]
The type used can be hardcoded for now (mind that in different templates, the type may change, so the hardcoded part must check which template is currently used). Later, we can either use categories for choosing the type or use the discussed "tagged type" feature that enables the template to tag one specific type with a special meaning. But maybe that feature is just a category with only one member. TBD.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
