### ISSUE TITLE
On http://prod-preview.openshift.io, the same backlog size (95) is always shown

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1277]
Regardless of how many new workitems are created.

![screenshot from 2017-03-23 15-41-41](https://cloud.githubusercontent.com/assets/642621/24267040/56dc84d4-0fdf-11e7-89ef-f79294c27505.png)

**Comment by vikram-raj** [comment]
This issue has been fixed in #1506.
