### ISSUE TITLE
On http://prod-preview.openshift.io, when viewing the contents of an iteration - the user must toggle board/backlog views to close the view

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1278]
To recreate this issue:

* From the backlog view, open an iteration, view the workitems in the iteration
* The user does not have a means to close the iteration view
* In order to view the full backlog again, the user must first view open the board view and then open the backlog view

**Comment by vikram-raj** [comment]
@ldimaggi Backlog at the top of the side panel is clickable. So you can view full backlog by clicking on the backlog. No need to toggle between the view to see the full backlog.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
