### ISSUE TITLE
Creating a Work Item shows no options

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#1282]
Attempted to create a new Work Item using the both prod-preview and the master branches of fabric8-planner and fabric8-ui in integrated mode. The full method for creating a Work Item is blank, with no options for selecting a type.

Pro-Preview:
<img width="1920" alt="screen shot 2017-03-23 at 8 00 25 pm" src="https://cloud.githubusercontent.com/assets/4032718/24275103/6e814916-1003-11e7-9ebf-2bd95eee5572.png">

Local Environment:
<img width="1920" alt="screen shot 2017-03-23 at 8 00 44 pm" src="https://cloud.githubusercontent.com/assets/4032718/24275104/6e826bfc-1003-11e7-998d-7d805e10800b.png">

**Comment by nimishamukherjee** [comment]
@mindreeper2420 local should work now.

**Comment by mindreeper2420** [comment]
Verified as working on prod-preview

<img width="1920" alt="screen shot 2017-03-24 at 8 58 37 am" src="https://cloud.githubusercontent.com/assets/4032718/24295223/1a55f842-1070-11e7-8655-389cb5065230.png">
