### ISSUE TITLE
[Bug]: Edit/Update comment is not working as expected

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1288]
Edit/Update comment is not working as expected
- Try save the updated comment , it keep on  adding "&amper; " how many time you hit "tick (save comment)"
button

Video Link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COS1ZOWFh2WUwxc28/view?usp=sharing

**Comment by naina-verma** [comment]
@debloper / @nimishamukherjee  can you please look into it !

**Comment by debloper** [comment]
Fixed by #1335, closing this.
