### ISSUE TITLE
Creator is Not Shown When Creating a Work Item (long form)

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#1295]
When creating a Work Item using the long form selection process (not quick add), the Creator is not shown and is replaced with 'Creator not found'.

According to the UX designs, the Creator should be set as soon as the Work Item panel is opened with the Title in the active state. Even though the Work Item has not been saved at this time, it should be shown to the user that they are indeed the creator of the new Work Item.

UX Design Link (Visual Design) - only for Creator reference (other parts may be outdated): https://redhat.invisionapp.com/share/Q5AFSN364#/213678970_A-0300-Default

Screenshot of current implementation:
<img width="785" alt="screen shot 2017-03-24 at 7 10 48 am" src="https://cloud.githubusercontent.com/assets/4032718/24291837/0c417f92-1061-11e7-9a30-87644a7d571a.png">

**Comment by pranavgore09** [comment]
@mindreeper2420 This is fixed now, can you please verify ?

**Comment by mindreeper2420** [comment]
@pranavgore09 I now have a broken user icon:
<img width="463" alt="screen shot 2017-04-26 at 7 06 07 am" src="https://cloud.githubusercontent.com/assets/4032718/25431509/dfa050d2-2a4e-11e7-98ee-2f5158f7ba2b.png">

**Comment by naina-verma** [comment]
verified
