### ISSUE TITLE
Inmemory mode Board view broken

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1296]
Inmemory mode Board view broken
its showing all elements in all states 
![screenshot from 2017-03-24 17-01-25](https://cloud.githubusercontent.com/assets/19172870/24292521/b0e45a18-10b3-11e7-81c0-10740086990e.png)

**Comment by naina-verma** [comment]
Due to this board.spec will fail!!

**Comment by debloper** [comment]
@naina-verma can you please re-verify, if this still is the case?

**Comment by naina-verma** [comment]
Verified
