### ISSUE TITLE
Kebab menu is not aligned correctly

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#1311]
The kebab menu (for items in the list view) is not aligned correctly, according to specs. The triangle connecting the menu to the icon should be directly below the kebab icon, with the menu flowing down and to the left.

**Incorrect Implementation:**
<img width="210" alt="screen shot 2017-03-24 at 11 53 16 am" src="https://cloud.githubusercontent.com/assets/4032718/24302367/c52c553c-1088-11e7-9eb2-ffce1a747b5a.png">

**Comment by SMahil** [comment]
@mindreeper2420 this bug is resolved. Please confirm

<img width="255" alt="screen shot 2017-04-04 at 2 45 55 pm" src="https://cloud.githubusercontent.com/assets/10396359/24649659/8253ea66-1945-11e7-9d49-2ab6027cc69e.png">

**Comment by mindreeper2420** [comment]
LGTM - verified on prod-preview
