### ISSUE TITLE
Non-Primary Button should not turn blue on hover

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#1315]
Buttons that are not considered Primary Buttons should not turn blue on hover.

Currently, the 'Cancel' button in the Create Iteration Modal turns blue when a 
<img width="628" alt="screen shot 2017-03-24 at 12 09 55 pm" src="https://cloud.githubusercontent.com/assets/4032718/24302999/d5063e58-108a-11e7-82c5-a7e18db3e9a3.png">
user hovers over it.

**Comment by naina-verma** [comment]
Verified
