### ISSUE TITLE
In the board view, the wrong user avatar is being used

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1322]
![screenshot from 2017-03-24 11-40-26](https://cloud.githubusercontent.com/assets/642621/24304810/1d9564e0-1091-11e7-98d4-b3a7bf843d4c.png)

**Comment by mindreeper2420** [comment]
the correct icon is `pficon-user` (http://www.patternfly.org/styles/icons/). The font family for PatternFly may need to be updated to use this icon.
