### ISSUE TITLE
Workitem comment and commit buttons are not displayed

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1323]
![screenshot from 2017-03-24 12-59-30](https://cloud.githubusercontent.com/assets/642621/24305007/d2b3c1dc-1091-11e7-91f5-bbf633401073.png)

**Comment by mindreeper2420** [comment]
@ldimaggi there is no commit/cancel buttons for the initial comment field. The commit/cancel are only found on the comments when editing a pre-existing one. The designs can be found here: https://redhat.invisionapp.com/share/Q6AAQVO8X on slide 10.

I can see how this is inconsistent, and a bug should be filed on fabric8-ux

**Comment by debloper** [comment]
I think this can be closed as INVALID/WONTFIX in this case.

**Comment by debloper** [comment]
I think this can be closed as INVALID/WONTFIX in this case.
