### ISSUE TITLE
Header areas in the WI are barely visible 

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1330]
![screenshot from 2017-03-24 13-24-36](https://cloud.githubusercontent.com/assets/642621/24305988/43c45474-1095-11e7-843c-c722620360f2.png)

**Comment by nimishamukherjee** [comment]
@ldimaggi can you let us know which portion you are referring to? I'm not able to figure out the issue here.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
