### ISSUE TITLE
In http://prod-preview.openshift.io - editing the ending date for an iteration does not save the correct date

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1339]
To recreate this issue:

* Create a new iteration, start the iteration
* Edit the iteration, select a new ending date
* Save the iteration 
* Edit the iteration - observe the ending date is not the date that was selected
* It looks like it is saving (the selected date - 1 day)

![screenshot from 2017-03-27 09-15-09](https://cloud.githubusercontent.com/assets/642621/24358128/176c42b6-12ce-11e7-9f86-5e8f99606fd2.png)

![screenshot from 2017-03-27 09-15-33](https://cloud.githubusercontent.com/assets/642621/24358139/1d4470fa-12ce-11e7-93c7-ec6714668a40.png)

**Comment by vikram-raj** [comment]
Hi @ldimaggi, Is this issue still exist? I am not able to regenerate this.

**Comment by naina-verma** [comment]
Verified !
