### ISSUE TITLE
In http://prod-preview.openshift.io, an iteration's description text box can be expanded beyond the edge of its dialog

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1340]
![screenshot from 2017-03-27 09-19-30](https://cloud.githubusercontent.com/assets/642621/24358267/a14ceb2a-12ce-11e7-9424-37680995611c.png)

Once the text box is expanded, it remains in that size after the iteration is saved and edited again.

**Comment by vikram-raj** [comment]
As I discuss with @muruGanesan we are blocking the user to resize the description field horizontally as well vertically.
