### ISSUE TITLE
In http://prod-preview.openshift.io, start/end dates cannot be specified when an iteration is created - but default values are assigned

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1341]
See attached screenshots - the user is not given the option of defining start and/or end dates when creating a new iteration. Default values are assigned and the user must edit the iteration to change these dates.

![screenshot from 2017-03-27 09-26-47](https://cloud.githubusercontent.com/assets/642621/24358818/5e8ebdca-12d0-11e7-8ae4-76449bab95ea.png)
![screenshot from 2017-03-27 09-27-31](https://cloud.githubusercontent.com/assets/642621/24358817/5e8944da-12d0-11e7-8b52-8ee6e2b2538f.png)

**Comment by Essjaysee** [comment]
Also, the dialog title should be "Edit Iteration" and the primary action button should be "Edit".  I see in the wireframes that I had the title right but the button wrong -- will fix now.

**Comment by vikram-raj** [comment]
@Essjaysee Do we allow the user to add start and end date while creating the iteration. 

I refer to this https://redhat.invisionapp.com/share/FR9R8G6B9#/screens/211880607 visual design. and select date field is not there.

**Comment by Essjaysee** [comment]
The wireframes were updated to include the date pickers on the create dialog: https://redhat.invisionapp.com/share/WSAJ8VUD3#/217273332_V2_Create_Iteration

It should be exactly the same date picker as used on the edit screen.  Thanks!

**Comment by vikram-raj** [comment]
@Essjaysee What will be the behavior if the user didn't select the start and end date while creating the iteration and come back to update the iteration then could we show empty start and end date field or filled with current date?

**Comment by Essjaysee** [comment]
@vikram-raj Not sure if you need this answer still now that the issue is closed, but in the case you describe, we would pre-fill the fields with a start date that is today and an end date that is some amount of time in the future. That end date depends on what methodology you chose (Agile or Scrum would be 2 weeks in the future, for example).

**Comment by nimishamukherjee** [comment]
@Essjaysee please have a look at the chat with @michaelkleinhenz and @muruGanesan, based on which @vikram-raj implemented the empty date behaviour.
![iterationdate](https://cloud.githubusercontent.com/assets/1892722/24894841/8beaa4a6-1eaa-11e7-8a00-3be91bfa05b3.png)

**Comment by maxandersen** [comment]
@Essjaysee at the moment we have *Zero* logic connected to the dates and they are supposed to be *optional* thus force feeding dates in here is just going to require users to maintain dates that are not correct/valuable to them.

We at least need a way to remove them to allow consistency.

Once we have process templates where we can set up rules for how dates should or should behave then we can put them in. Does that work for you @Essjaysee ?
