### ISSUE TITLE
Angular changes in UI are affecting multiple UI Functional automated Selenium/Protractor tests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1342]
The issues - where UI elements cannot be found - seem to be limited to the workitem detail page. 

We need to find a workaround to this issue or some tests will not run.

**Comment by naina-verma** [comment]
https://github.com/fabric8io/fabric8-planner/issues/1362 for now all the tests are broken, am blocked by this issue.
