### ISSUE TITLE
Most of the UI Functional tests are failing

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1362]
On Tuesday night at 23:00 Boston time - when I created a PR for my final changes, the tests were showing:

87 specs, 2 failures
(the failures were due to a known bug)

9 hours later, at 08:00 Boston time on Wednesday, I updated from master, ran the tests, and saw these results:
87 specs, 72 failures

**Comment by naina-verma** [comment]
@sanbornsen,
This video has detail explanation for the failures. 
 Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COMWl1OUR3eWl4R00/view?usp=sharing

**Comment by sanbornsen** [comment]
@ldimaggi @naina-verma Don't need to sweat so hard guys, I am quite aware of the breakage. Everything will be in order soon. There are some major changes has happened to the services and the way we take data from the APIs and that's the reason of the failure. I need to implement the similar concept in our mocks.
