### ISSUE TITLE
On http://prod-preview.openshift.io - Latin filler text is seen

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1369]
See enclosed screenshot:

![screenshot from 2017-03-28 10-22-51](https://cloud.githubusercontent.com/assets/642621/24506208/c005652a-152a-11e7-827e-00b5bde96bbc.png)

**Comment by nimishamukherjee** [comment]
@ldimaggi this needs to be logged under https://github.com/fabric8io/fabric8-ui
Creation of space happens on Fabric UI

**Comment by ldimaggi** [comment]
Out of date - no longer an issues - closing as part of pre-bug-triage tasks.
