### ISSUE TITLE
On http://prod-preview.openshift.io, logging with Firefox presents the user with a blank screen

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1372]
This happens at the 18 second mark of the referenced screencast:

https://drive.google.com/open?id=0B1s-ZoxD8FjUcmRqSlpUQXBzT3M

**Comment by mindreeper2420** [comment]
@ldimaggi can you file this under the www.openshift.io repo and close this issue? This is most likely a problem with routing or caching from the homepage and is not related to Planner.

**Comment by ldimaggi** [comment]
https://github.com/openshiftio/www.openshift.io/issues/68
