### ISSUE TITLE
On https://prod-preview.openshift.io, registration does not ask for + registration code

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1388]
To recreate issue:

* Access:  https://prod-preview.openshift.io
* Select "Register for Developer Preview"
* The email and code fields are not displayed

**Comment by mindreeper2420** [comment]
This is done on purpose and not a bug - the workflow still needs to be dropped into place.

Any bugs related to the homepage should be filed to the www.openshift.io repo (not part of Fabric8). Thanks!
