### ISSUE TITLE
On https://prod-preview.openshift.io - ubable to associate workitems with iterations

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1399]
This started failing today - steps to recreate:

* Create a workitem
* Create an iteration
* Click on  the workitem's kebab and select 'associate with iteration'
* See the attached screenshot for the dialog displayed
* See the screencast here for the results - the user is unable to associate the workitem with the iteration
https://drive.google.com/open?id=0B1s-ZoxD8FjURzJyZWtWN24zSUU

![screenshot from 2017-03-31 16-02-27](https://cloud.githubusercontent.com/assets/642621/24568166/e4ff2154-162e-11e7-95ee-5e2ac315c3af.png)

**Comment by nimishamukherjee** [comment]
@ldimaggi can you confirm if you were logged in or not?

**Comment by naina-verma** [comment]
@nimishamukherjee , User is logged in and try to Reassociate Iteration!
Due to this bug test automation also fails

**Comment by vikram-raj** [comment]
@naina-verma or @ldimaggi Can you verify if this issue still exists? I am not able to recreate it.

**Comment by naina-verma** [comment]
Verified !
