### ISSUE TITLE
Add comments doesn't clear text box after adding comment 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1432]
Add comments doesn't clear text box after adding comment 
Video link https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COTHU4YjM0bGFsX1E/view?usp=sharing

![screenshot from 2017-04-03 17-09-54](https://cloud.githubusercontent.com/assets/19172870/24607640/65d5c130-1890-11e7-9650-5418ee52a4bd.png)

**Comment by naina-verma** [comment]
@debloper , @sanbornsen  can you please look into it!

**Comment by debloper** [comment]
Recent changes added this regression. Will address in new patch.

**Comment by naina-verma** [comment]
@debloper , okay!

**Comment by debloper** [comment]
Fixed.
