### ISSUE TITLE
Building from master/src - Cannot access Planner in UI

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1436]
Steps to recreate:
* Build from source - git@github.com:fabric8io/fabric8-planner.git
* Run scripts/run-integration.sh

Error returned in Chrome browser console is:
Unhandled Promise rejection: Cannot find module "@angular/animations" ; Zone: angular ; Task: Promise.then ; Value: ZoneAwareError {__zone_symbol__error: Error: Cannot find module "@angular/animations"
    at Object.../fabric8-planner/dist-watch/src/app/……}

Browser log file is attached

[localhost-1491242017417log.txt](https://github.com/fabric8io/fabric8-planner/files/890895/localhost-1491242017417log.txt)

**Comment by almightytest** [comment]
Seeing this now:

error_handler.ts:1 ERROR Error: Uncaught (in promise): Error: Found the synthetic property @slideInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
Error: Found the synthetic property @slideInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (http://localhost:3000/vendor.bundle.js:27345:15) [angular]

![screenshot from 2017-04-03 22-51-06](https://cloud.githubusercontent.com/assets/23330096/24640016/b79af68a-18c1-11e7-855a-f20fe34b2880.png)

**Comment by ldimaggi** [comment]
Out of date - no longer an issues - closing as part of pre-bug-triage tasks.
