### ISSUE TITLE
Remove unused ghooks dependency

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-planner#145]
Project specifies devDependency ghooks which seems to be not used.

It transitively brings 4 additional dependencies, one of which is cross-spaw-async which causes the following warning during `npm install`

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
```

**Comment by joshuawilson** [comment]
@kwk @kbsingh do you have an opinion about using ghooks. I had tried early on to configure them. I wasn't able to get them to work quickly enough so I abandoned the idea for later. I am sure I can get it to work if we want it. Thoughts?

**Comment by ppitonak** [comment]
What did you want to use it for?

**Comment by joshuawilson** [comment]
git provides a way to hook some git actions (like commit, push) to run custom scripts. These hooks run at different moments of the actions, and you can use them to improve your workflow in several ways. Some examples are preventing a commit to happen if a test fails, or running some kind of build tool before pushing.

**Comment by joshuawilson** [comment]
At this point, I have yet to come up with a good reason to use ghooks. However when I remove them, they create a lot of warnings. So for now, I will leave them in and close this. 

If they become a problem, please open this up and I will readdress the issue.

**Comment by ppitonak** [comment]
For the record, when I removed ghooks from devDependencies, some git commands showed these warnings:

```
ghooks not found!
Make sure you have it installed on your "node_modules".
Skipping git hooks.
```

To solve this, you need to remove all hooks generated by `ghooks`:

```
cd almighty-ui/.git/hooks
rm applypatch-msg commit-msg post-applypatch post-checkout post-commit post-merge post-receive post-rewrite post-update pre-applypatch pre-auto-gc pre-commit prepare-commit-msg pre-push pre-rebase pre-receive update
```

**Comment by joshuawilson** [comment]
Opening to follow @ppitonak advise.

**Comment by ppitonak** [comment]
ghooks is now deprecated https://github.com/gtramontina/ghooks#deprecated
