### ISSUE TITLE
New Iteration vanish from screen while clicking on it

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1463]
New Iteration vanish from screen while clicking on it
This behavior is happening on Standalone and Prod.preview both
- New Iteration disappears while clicking on it
- Display back on reload of the page 
Video Link :https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COMjhvbDBFV3ByUjA/view?usp=sharing

**Comment by naina-verma** [comment]
@vikram-raj , @sanbornsen  can you please look into it!

**Comment by vikram-raj** [comment]
Fixed in #1688

**Comment by naina-verma** [comment]
Verified !
