### ISSUE TITLE
Delete Comment Dialog box implementation is wrong

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#1473]
Delete Comment Dialog box opens up differently

<img width="1440" alt="screen shot 2017-04-05 at 3 28 26 pm" src="https://cloud.githubusercontent.com/assets/10396359/24703209/dc98915e-1a1f-11e7-8d8d-b06950b1ecb4.png">

Here is the invision link for Visuals:  https://redhat.invisionapp.com/share/Q6AAQVO8X#/screens/217205690

**Comment by debloper** [comment]
It is fixed now...
