### ISSUE TITLE
Not clear what tickbox is for

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-planner#1491]
http://www.screencast.com/t/tF66gkcByUap

**Comment by catrobson** [comment]
Checkboxes are for multi-select.  For now this will only allow you to move those items up and down in your list.  In the future this could enable other behaviors like bulk-delete, bulk-edit some field, etc.

https://redhat.invisionapp.com/share/YVA4PGYA3#/225834565_Multi-Select

**Comment by pmuir** [comment]
Ok, as a user, this behaviour is very non obvious. I had to hunt around to
understand it

**Comment by Essjaysee** [comment]
We'll be doing usability testing on the UI in the next few weeks, and will be sure to capture additional data on the checkboxes.

**Comment by nimishamukherjee** [comment]
Checkbox removed for summit.
