### ISSUE TITLE
On https://prod-preview.openshift.io - creating a new iteration displays the root iteration as undefined in the iteration list

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1502]
![screenshot from 2017-04-05 14-46-14](https://cloud.githubusercontent.com/assets/642621/24721555/b458d674-1a0e-11e7-8ab6-d2d77c65a9dc.png)

**Comment by vikram-raj** [comment]
Hi @ldimaggi, It is because we don't get `resolved_parent_path` attributes in GET iteration API. And there is [PR](https://github.com/almighty/almighty-core/pull/990) for this.

**Comment by vikram-raj** [comment]
PR get merged and it has been fixed.
