### ISSUE TITLE
Nested iterations names/paths display is truncated when the path exceeds the width of its screen column

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1503]
Enhancement: Allow the user to resize the vertical panel in which the iterations are displayed

![screenshot from 2017-04-05 14-53-03](https://cloud.githubusercontent.com/assets/642621/24721922/cabe7f6c-1a0f-11e7-8866-8df1817ad4d5.png)

**Comment by nimishamukherjee** [comment]
@ldimaggi the text wraps now. Please verify.
![iteration](https://cloud.githubusercontent.com/assets/1892722/25088726/046246c4-2396-11e7-97ab-b68000187f4e.png)

**Comment by naina-verma** [comment]
Verified !
