### ISSUE TITLE
On https://prod-preview.openshift.io, cannot associate an area with a workitem

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1504]
The save button for the area selection is missing (the cancel "x" button is present):

**Comment by ldimaggi** [comment]
![screenshot from 2017-04-05 14-56-32](https://cloud.githubusercontent.com/assets/642621/24722041/341d6fb8-1a10-11e7-83d7-49669aa00cbd.png)

**Comment by nimishamukherjee** [comment]
Issue fixed @ldimaggi. Please verify.

**Comment by naina-verma** [comment]
Verified !
