### ISSUE TITLE
Two scrollbars on Detail view page 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1522]
Two scrollbars on Detail view page 
Steps to reproduce:
- Generate plenty on comments 
and check that the Detail view page shows up 2 scrollbars

Video Link:
https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COOHZNRkNrN0NIc1U/view?usp=sharing

**Comment by naina-verma** [comment]
@SMahil can you please look into it !

**Comment by SMahil** [comment]
@naina-verma I have checked on chrome and firefox, It seems fine to me, there are no two scrollbars.

**Comment by SMahil** [comment]
@naina-verma after creating more than 20 comments refresh the page , I am unable to see only 20 comments. Rest are getting deleted

**Comment by nimishamukherjee** [comment]
@naina-verma please verify

**Comment by naina-verma** [comment]
Verified !
