### ISSUE TITLE
Create Iteration: Parent Dropdown broken

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#1523]
The parent dropdown needs more love:
- it has the default value "null". Should be something like "None" in disabled (grey/italics) to indicate this is the "no parent" selector.
- the dropdown can not be closed without selecting a value. Clicking on the down caret does not do anything.
- on prod, I currently have an entry in the select box named "//Demo", with two "/" at the beginning.
- the field is editable. It should not.
- the down caret button is not flush with the input box border. The bottom has a gap.
- most of the above applies to the dialog on the "plus" button as well as the "create child" dialog on the current iteration.

**Comment by vikram-raj** [comment]
- it has the default value "null". Should be something like "None" in disabled (grey/italics) to indicate this is the "no parent" selector. Fix in #1520 
- the down caret button is not flush with the input box border. The bottom has a gap. Fix in #1520

**Comment by vikram-raj** [comment]
@michaelkleinhenz can you please explain this point?
- the field is editable. It should not.

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz UX specifies the field to be a type ahead drop down.

**Comment by naina-verma** [comment]
Verified !
