### ISSUE TITLE
Workitem Detail Page overlaps Iteration Dialog box

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#1533]
**Steps to reproduce:**
1. Click on a workitem. Its detail view comes up.
2. Click on "+" button to create new iteration

When a new dialog box opens, Workitem detail Page should automatically close.

![screenshot from 2017-04-06 17-42-47](https://cloud.githubusercontent.com/assets/6303309/24754846/a8e4d36e-1af5-11e7-9e49-6ef9fec139b4.png)

**Comment by catrobson** [comment]
The work item should stay open when the user selects to create an new iteration, but would be behind the modal and behind the screen shadowbox.  Once the iteration is created, the planner should open that iteration on screen, which would close the work item detail and be showing a new list view for just the work items in that iteration (empty state at that point).

**Comment by DhritiShikhar** [comment]
@catrobson that looks good.

**Comment by naina-verma** [comment]
Verified on Red Hat ( v1.27.19 Build#262 2017-04-19T08:01:25+00:00 )
