### ISSUE TITLE
Stop using /api/users/ to get the list of all users

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-planner#1538]
Use /api/users/:userID instead to get info about particular user.
If you need a list of users for particular space then you can use `GET /api/spaces/:spaceID/collaborators/`
Details are here: https://github.com/almighty/almighty-core/pull/1116

/api/users/ in the way how it works now won't scale. It will just die if there are many users.

**Comment by alexeykazakov** [comment]
@michaelkleinhenz ^^^

**Comment by aslakknutsen** [comment]
@alexeykazakov @michaelkleinhenz Follow the 'self' link on the user object in question, do not construct urls. creator, owned-by, assigness etc etc

**Comment by alexeykazakov** [comment]
@aslakknutsen there is a link in every space object: /api/spaces/:spaceID/collaborators/ which can be used  to get the list for the assignee pulldown.

**Comment by alexeykazakov** [comment]
FYI. The list of collaborators will be empty for old spaces - the spaces we created before 2017-3-16. There is no KC resources associated with those spaces.
