### ISSUE TITLE
On https://prod-preview.openshift.io/ the space homepage includes a description field for the space

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#1551]
The user is not given an opportunity to write text into the field.

![screenshot from 2017-04-07 12-24-18](https://cloud.githubusercontent.com/assets/642621/24809393/5cb14d40-1b8d-11e7-9d26-b807955a72ea.png)

**Comment by mindreeper2420** [comment]
@ldimaggi - is that one of your Spaces or someone else's? If it is your's, then you can edit it. Hover over the description field and a pencil will pop up. Just click inside to edit and click outside to save. 

Users who did not create the Space cannot edit the Description.

**Comment by ldimaggi** [comment]
Adam is correct!
