### ISSUE TITLE
Full area path not shown on workitem detail 

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-planner#1556]
CC: @maxandersen 

Steps to reproduce:

1. Assign workitem to a sub-area like "parent/child1/child2"
2. Check workitem area field - it shows "child2" , instead it should be "parent/child1/child2"

**Comment by nimishamukherjee** [comment]
@sbose78 @maxandersen do you still face this issue?
I could use nested areas with the complete path now.

![area1](https://cloud.githubusercontent.com/assets/1892722/25124996/0470a09c-244b-11e7-9a53-051e720f6ac6.png)
![area2](https://cloud.githubusercontent.com/assets/1892722/25125006/08fc9e72-244b-11e7-9f2d-68e10c1e08e4.png)

**Comment by naina-verma** [comment]
Verified
