### ISSUE TITLE
Unable to start iteration if there already  iteration in Current iterations

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1593]
Unable to start iteration if there already  iteration in Current iterations

Scenario 1
- Start a iteration 
- Click on another future iteration and try to start it
Expected : it should show error message we can't start this iteration because already one iteration is running 
Actual : It doesn't throw any error message and doesn't do anything on UI

Scenario 2
- Start a iteration
- Click on some other future iteration to Start (Replicate scenario 1)
- Close the Current iteration
- Refresh the page 
- Try starting future iteration 
Expected behavior : it should start the future iteration
Actual : unable to start future iterations

Video Link: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COelM4RXdEOHdLdW8/view?usp=sharing

**Comment by naina-verma** [comment]
@michaelkleinhenz , @sanbornsen can you please take a look into it!

**Comment by nimishamukherjee** [comment]
@naina-verma start/stop of iteration works fine on prod peview.

What we need to fix is this message - There is already a current iteration for FIXME. You must close the current iteration before starting this one.

**Comment by naina-verma** [comment]
@nimishamukherjee , i am not seeing any toast notification on production for this issue ! Can you plz check also.

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee @naina-verma created a PR for fixing the error message: #1716.

**Comment by naina-verma** [comment]
verified
