### ISSUE TITLE
[Bug]:Word wrap broken for iterations side panel 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1594]
[Bug]:Word wrap broken for iterations side panel 
Steps to reproduce 
- Create a iteration / child iteration
- it's name should contain more than 50-60 characters 
- Save it
Expected : It should be word wraped and show minimal chars on left panel

Actual: it is blocking the user to create more iterations  and  word wraps looks broken to entire screen.
User hits a **dead lock condition with** this case (for iterations ). because user can neither create , start ,edit and see the progress of the iterations

Video Link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COVjlEN1ZnVUR2TVE/view?usp=sharing

**Comment by naina-verma** [comment]
@michaelkleinhenz , @sanbornsen @vikram-raj please look into it

**Comment by nimishamukherjee** [comment]
@naina-verma please verify
![iteration](https://cloud.githubusercontent.com/assets/1892722/25086607/78baffc6-2386-11e7-9e8b-d47bdb8e11cd.png)

**Comment by naina-verma** [comment]
@nimishamukherjee can you plz give me a refernce PR!

**Comment by naina-verma** [comment]
Verified on production Works fine! 
 Red Hat ( v1.27.19 Build#262 2017-04-19T08:01:25+00:00 )
