### ISSUE TITLE
[BUG]: WI from other spaces/ iterations shouldn't be linked !

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1597]
[BUG]: WI from other spaces/ iterations shouldn't be linked !
Steps to reproduce
Scenario 1
- Create a WI planner item
- Try to link this WI with some WI which exists in another Iteration/Space (Not same iteration/Space)
In this case , it should not show WI to link from other iterations (Not sure @michaelkleinhenz can tell more about it)

Scenario 2
- Create a WI 
- try to link WI with some other WI which has incompatible WI link type 

In Scenario 2 it should throw a Error message saying "Cant link WI with this  link type"

**Comment by pranavgore09** [comment]
https://github.com/fabric8io/fabric8-planner/issues/1604 is taking care of scenario 1.

**Comment by michaelkleinhenz** [comment]
#1604 is closed. Does this fix this issue? @naina-verma 
@kwk is scenario 2 an issue at all?

**Comment by kwk** [comment]
> @kwk is scenario 2 an issue at all?

I don't think that scenario 2 is an issue because the core will reject incompatible types.

**Comment by naina-verma** [comment]
Verified
