### ISSUE TITLE
Planner Board View - Calling out work item type dropdown with label

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1659]
There was a request for the item type dropdown to be more obvious that it is required and driving the board view.  This is a minimal fix to try to call more visual attention to the dropdown and give it some context, to just add a label "Currently showing:" in front of the dropdown.

![currentlyshowingwitype](https://cloud.githubusercontent.com/assets/3739227/25153070/349f4bb6-2459-11e7-8057-d5ccb17911ca.jpg)

**Comment by mindreeper2420** [comment]
PR submitted: https://github.com/fabric8io/fabric8-planner/pull/1660
