### ISSUE TITLE
Iteration Save/cancel button alignment looks distorted with long iteration names in dropdown

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1678]
Iteration Save button looks distorted with long iteration names in dropdown

![screenshot from 2017-04-19 16-57-20](https://cloud.githubusercontent.com/assets/19172870/25177972/91feadb0-2521-11e7-85e9-d0023cc51b94.png)

**Comment by debloper** [comment]
Can't reproduce.

![screenshot from 2017-04-21 17-18-39](https://cloud.githubusercontent.com/assets/536060/25276234/c71b848c-26b6-11e7-9ec7-30017e3367db.png)

**Comment by naina-verma** [comment]
Verified !
