### ISSUE TITLE
Associating WI from Kebab , distorted dropdown for iteration list with long strings

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1679]
Associating WI from Kebab , distorted dropdown for iteration list with long strings

![screenshot from 2017-04-19 17-01-55](https://cloud.githubusercontent.com/assets/19172870/25178152/405b12a4-2522-11e7-8197-6ea97ea3f013.png)
![screenshot from 2017-04-19 17-02-09](https://cloud.githubusercontent.com/assets/19172870/25178154/40cd928e-2522-11e7-95af-6c0ca5457868.png)

**Comment by vikram-raj** [comment]
@mindreeper2420 Do we need type ahead drop in the associate iteration modal?

**Comment by debloper** [comment]
I think here we need to set a max width and overflow hidden, at least for the time being.
There's no real *solution* to this problem.

**Comment by vikram-raj** [comment]
fixed in https://github.com/fabric8io/fabric8-planner/pull/1744

**Comment by naina-verma** [comment]
Verified !
