### ISSUE TITLE
Not able to create an iteration under the root iteration

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-planner#1686]
Project 1 is the root iteration. Project 1 does not appear in the parent iteration drop down.
I can type /Project 1 and set it as the parent iteration.

![iterationdd](https://cloud.githubusercontent.com/assets/1892722/25190650/80afa90a-254a-11e7-9e4b-5980ef8e6179.png)

![nomatch](https://cloud.githubusercontent.com/assets/1892722/25190659/878a5a40-254a-11e7-9a38-582384b6466c.png)

**Comment by vikram-raj** [comment]
We are not listing the root iteration anywhere. 
By default iteration created under root iteration if you not select any iteration from the list.

**Comment by maxandersen** [comment]
Any reason why not listing the root area ? We are listing the root iteration in multiple places "/Project 1/Mad Rush" contains "/Project 1/" that is is the root area.

And there has to be something in the list to represent root area and/or "None" which means root area.

Current behavior is inconsistent.

**Comment by vikram-raj** [comment]
@maxandersen One reason for not showing the root iteration in side panel is that the user has no permission to start the root iteration. So we are showing it in parent path only.

**Comment by maxandersen** [comment]
> @maxandersen One reason for not showing the root iteration in side panel is that the user has no permission to start the root iteration. So we are showing it in parent path only.

I don't follow - this is about iteration selection for parent or workitem, something you will definitely need the root iteration for.

**Comment by vikram-raj** [comment]
@maxandersen This is for iteration selection for the parent. While creating the new iteration. But now we are showing the root iteration in the dropdown.

**Comment by nimishamukherjee** [comment]
Issue fixed.
