### ISSUE TITLE
WorkItem Assignee: Unassign not working

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#1705]
How to reproduce?
1. Click on assignee search bar. A drop down menu will appear.
2. Select an assignee.
3. Again click on assignee search bar. A drop down menu will appear.
4. Click on Unassign.

![screenshot from 2017-04-20 14-54-42](https://cloud.githubusercontent.com/assets/6303309/25223701/bd0e326a-25d9-11e7-9bd1-973f834cc237.png)

**Comment by vikram-raj** [comment]
It is working on prod-prev. @naina-verma can you please verify this.

**Comment by DhritiShikhar** [comment]
@vikram-raj @naina-verma now its working for me as well. I will close this one.
