### ISSUE TITLE
WorkItem Assignee does not display correct User Image

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#1706]
How to reproduce?

1. Click on assignee search bar. You will find a list of assignee and their profile picture
![screenshot from 2017-04-20 15-10-48](https://cloud.githubusercontent.com/assets/6303309/25224316/aa537f5c-25db-11e7-984b-fbb7253d4b5b.png)

2. Select an assignee. The assignee component sets a default image instead of using the actual profile picture which is displayed in the list
![screenshot from 2017-04-20 15-12-05](https://cloud.githubusercontent.com/assets/6303309/25224360/cdc97b4e-25db-11e7-9266-1dddd5441c27.png)

**Comment by naina-verma** [comment]
@DhritiShikhar , this works for me ! 
Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COUkh4bEhIWGFWR00/view?usp=sharing

**Comment by DhritiShikhar** [comment]
@naina-verma +1 now its working for me as well. I will close this issue.
