### ISSUE TITLE
Re-associate iteration messages are not proper

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1708]
Re-associate iteration messages are not proper

Steps to reproduce 
- click on kebab to associate a iteration 
it gives an incomplete message that 
"iteration is currently associated with __
Re-associate iteration with 'dropdown'"

It should show message with already associated iteration if  not it should say "None"  
![screenshot from 2017-04-20 16-40-21](https://cloud.githubusercontent.com/assets/19172870/25227958/126a131a-25e8-11e7-9ebf-21c193aae15a.png)

Video link: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COX3M5OUZGLXZtZ3M/view?usp=sharing

**Comment by vikram-raj** [comment]
Fixed in https://github.com/fabric8io/fabric8-planner/pull/1744

**Comment by naina-verma** [comment]
Verified!
