### ISSUE TITLE
Iterations list not updated on kebab re-association dialog

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1709]
Iterations list not updated on kebab re-association dialog
Steps to reproduce 
- create a new iteration
- click kebab and select re-associate 
- you wont see the newly created iteration into the drop down list 

video link: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COdjBpNGFTWGIzNzQ/view?usp=sharing

**Comment by vikram-raj** [comment]
Fixed in https://github.com/fabric8io/fabric8-planner/pull/1744

**Comment by naina-verma** [comment]
Verified !
