### ISSUE TITLE
Iteration side-panel should maintain selection across list and board view

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1712]
The side panel should maintain the current state when moving between the board and list views.  

If I am selected on backlog, I should be selected on backlog when moving to the other view.  If I have selected an iteration in the left hand panel, then that should maintain selection of the iteration.

Also, any expand/collapse actions I have taken should also be maintained across views, making sure that my view of iterations isn't changing between views.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz can you take a look?

**Comment by sanbornsen** [comment]
I was not informed about this behaviour. I am taking this up.

**Comment by sanbornsen** [comment]
Fixes are in both planner and platform
https://github.com/fabric8io/fabric8-planner/pull/1720
https://github.com/fabric8io/fabric8-ui/pull/961
They are not dependent though
