### ISSUE TITLE
Regression: Iteration Panel Click Points

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#1717]
In the current version of the product, a user has to specifically click on the Iteration title in order to select that iteration. In previous versions, a user could click anywhere in the Iteration area to select that specific Iteration.

![iterationpanel](https://cloud.githubusercontent.com/assets/4032718/25258414/42484a28-260d-11e7-9f70-da4f702ac071.png)

When the Iteration is active, it is highlighted as such:
<img width="490" alt="screen shot 2017-04-20 at 9 07 01 pm" src="https://cloud.githubusercontent.com/assets/4032718/25258424/5d6638a6-260d-11e7-8134-cb300984e09f.png">

**Comment by naina-verma** [comment]
Verified !
