### ISSUE TITLE
distorted Associtation iteration div (not fitting itself with increasing dropdwon list)

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1718]
distorted Association iteration div (not fitting itself with increasing dropdwon list)
![screenshot from 2017-04-21 13-10-31](https://cloud.githubusercontent.com/assets/19172870/25270968/14a9ff56-26a0-11e7-841c-a659c7d38069.png)

**Comment by debloper** [comment]
Steps to reproduce?

Also, what's the issue exactly? The tooltip looks fine on my setup.

**Comment by vikram-raj** [comment]
Fixed in https://github.com/fabric8io/fabric8-planner/pull/1744

**Comment by naina-verma** [comment]
@vikram-raj am I can reproduce this bug !

![screenshot from 2017-05-10 16-37-27](https://cloud.githubusercontent.com/assets/19172870/25895786/06b7cec4-359f-11e7-8769-c0536a5c4016.png)

**Comment by naina-verma** [comment]
Verified
