### ISSUE TITLE
Bug[Mock]: For iterations looks broken 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1735]
Bug[Mock]: For iterations looks broken 

- cannot create a child iteration 
- can't start a newly created iteration
- Iteration is not showing the Parent iterations 

Video: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COZ0xRWkR5TXpfR2c/view?usp=sharing

**Comment by michaelkleinhenz** [comment]
Create works for me, also showing. But not starting. I'll look into it.
