### ISSUE TITLE
distorted layout of board view with long string title/description 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#1748]
Distorted layout of board view with long string title/description 

Expected behavior : the words should be wrapped / truncate for title and description 

Video link:https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COMUJQRmFZLTZGcTg/view?usp=sharing

**Comment by naina-verma** [comment]
@SMahil  can you please look into it

**Comment by catrobson** [comment]
@mindreeper2420 is looking into fixing board view title text.

**Comment by SMahil** [comment]
This issue is already fixed in below PR:

https://github.com/fabric8io/fabric8-planner/pull/1772

**Comment by naina-verma** [comment]
@SMahil am able to reproduce this issue on openshiftio

**Comment by naina-verma** [comment]
Verified
