### ISSUE TITLE
Remove link type from iteration panel and work item names

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-planner#1764]
In the iteration panel, iteration names should not be blue links and the entire iteration row should be selectable.  Also captured in this issue:  https://github.com/fabric8io/fabric8-planner/issues/1717

Also for individual work items in the list view and board view, the names should not be links, but rather just black text.  Selecting the whole row or the whole card should bring up the work item detail panel.

This PR caused this change in behavior: https://github.com/fabric8io/fabric8-planner/pull/1688

**Comment by michaelkleinhenz** [comment]
Created PR, #1766. Please check the colors of the titles as they now changed. @sanbornsen please check if that works, I just moved the [routerLink] attributes to move the clickable area up.
