### ISSUE TITLE
"Saving Work Item" spinnings forever

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-planner#1915]
_From @burrsutter on May 20, 2017 23:59_

https://screencast.com/t/oV50taQ9

Though the workitem appears to be created and landed
https://openshift.io/burrsutter/myspace/plan/detail/817

_Copied from original issue: openshiftio/openshift.io#174_

**Comment by nimishamukherjee** [comment]
@joshuawilson fix is on production. Can you verify?

**Comment by joshuawilson** [comment]
I can confirm the spinner goes away
