### ISSUE TITLE
Workitems created from integrated planner adds wrong markups

### ISSUE THREAD

**Issue by debloper** [fabric8io/fabric8-planner#1964]
![screenshot from 2017-06-05 18-39-29](https://cloud.githubusercontent.com/assets/536060/26785112/7ad16232-4a1e-11e7-9596-ba925ca0d6ab.png)

The WI ID has an extra `workItemType">` prepended `<span>` element breaking the UI.

**Comment by vikram-raj** [comment]
Fixed in https://github.com/fabric8io/fabric8-planner/pull/1952
