### ISSUE TITLE
When I hover over my profile pic in wi comments ,the legend is in a wrong position 

### ISSUE THREAD

**Issue by hectorj2f** [fabric8io/fabric8-planner#1968]
When I pass my mouse over my profile picture in a wi's comment, I see the legend far from where my mouse is.
![screen shot 2017-06-06 at 11 11 01 am](https://cloud.githubusercontent.com/assets/3602792/26822711/5497a8a0-4aab-11e7-9924-380bc2bbb925.png)

**Comment by debloper** [comment]
Diagnosed the reason for this issue. This happens when the WI detail view has been scrolled up.

Presumably a bug in the tooltip module miscalculating the tooltip position being unaware of the element's position, and try to interpret it relatively to the detail container.

**Comment by debloper** [comment]
Found the solution, submitting a patch.

Meanwhile, this issue spans to almost all the tooltips we have and same solutions may apply there, but I'm not sure about the side-effects of this approach, although this is from official documentation.

As a solution, ngx-tooltip suggests adding a directive to append the tooltip element to the `body` itself, but it *may* cause some DOM issues (may very well be just fine, idk).
