### ISSUE TITLE
Use Headless X-Server for Functional Testing across all supported browsers

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#201]
The Jenkins job and/or the functional tests should use xvfb for testing. That would allow for other 
browsers to be used for the functional tests. There is a Jenkins plugin available at:

https://wiki.jenkins-ci.org/display/JENKINS/Xvfb+Plugin

As an alternative, this could also be integrated in the bash test runner like:

```
Xvfb :99 &
export DISPLAY=:99
./run_functional_tests.sh (or something else)
```

The CentOS package needed is:

`xorg-x11-server-Xvfb.x86_64 : A X Windows System virtual framebuffer X server`

**Comment by ppitonak** [comment]
Since the tests run inside a Docker container, Jenkins plugin would be probably too difficult to configure because the Xvfb would run on Jenkins slave, not inside container. 

It seems that easier way would be to install Xvfb and Firefox/Chrome in Docker container, i.e. add necessary packages in https://github.com/almighty/almighty-ui/blob/master/Dockerfile.builder#L25

**Comment by joshuawilson** [comment]
@ldimaggi is this something you still plan to work on?

**Comment by ldimaggi** [comment]
Yes - we need to look t this in the 124 sprint - we want to be able to run tests against actual browsers in a headless configuration.

**Comment by ppitonak** [comment]
Another option is to use services like SauceLabs

**Comment by ldimaggi** [comment]
This is easier to setup/use:

xvfb-run ./run_functional_tests.sh

**Comment by ldimaggi** [comment]
And - when the tests run headless - we should add a screenshot recorder to capture screenshots of failed tests:  https://www.npmjs.com/package/protractor-jasmine2-screenshot-reporter

Sample configuration:

```

var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

var reporter = new HtmlScreenshotReporter({
  dest: 'target/screenshots',
  filename: 'my-report.html',
  reportOnlyFailedSpecs: false,
  captureOnlyFailedSpecs: true
});

exports.config = {
    useAllAngular2AppRoots: true,
    getPageTimeout: 30000,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['src/tests/**/*.spec.js'],

multiCapabilities: [
	{ 
        'browserName': 'firefox',
        'firefox.binary': "/usr/bin/firefox",
        'firefox.cli.args': ['--webdriver-loglevel=ERROR', '--local-storage-path=/tmp/phantom_' + Math.random()]
 	}

/*	{
        'browserName': 'phantomjs',
        'phantomjs.binary.path': require('phantomjs').path,
        'phantomjs.cli.args': ['--webdriver-loglevel=ERROR', '--local-storage-path=/tmp/phantom_' + Math.random()]
	}   */
	],
maxSessions: 1,

  // Setup the report before any tests start
  beforeLaunch: function() {
    return new Promise(function(resolve){
      reporter.beforeLaunch(resolve);
    });
  },

  // Assign the test reporter to each running instance
  onPrepare: function() {
    jasmine.getEnv().addReporter(reporter);
  },

  // Close the report after all tests finish
  afterLaunch: function(exitCode) {
    return new Promise(function(resolve){
      reporter.afterLaunch(resolve.bind(this, exitCode));
    });
  }

}

```

**Comment by ldimaggi** [comment]
Steps to perform:

- Clone this job - https://ci.centos.org/view/Devtools/job/devtools-almighty-ui/ - and make these modifications:

- Install chrome, firefox, Xvfb, https://www.npmjs.com/package/protractor-jasmine2-screenshot-reporter

- Configure the test to be run with this CLI command: xvfb-run ./run_functional_tests.sh

- Configure the job to run nightly

- Configure the job to report all results (pass or fail) in email to: ldimaggi@redhat.com, nverma@redhat.com, mkleinhe@redhat.com

- Configure the job to retain the 'target' directory in the workspace after each job run.

- Replace the contents of protractor.config.js with this:


```

var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

var reporter = new HtmlScreenshotReporter({
  dest: 'target/screenshots',
  filename: 'my-report.html',
  reportOnlyFailedSpecs: false,
  captureOnlyFailedSpecs: true
});

exports.config = {
    useAllAngular2AppRoots: true,
    getPageTimeout: 30000,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['src/tests/**/*.spec.js'],

multiCapabilities: [
	{ 
        'browserName': 'firefox',
        'firefox.binary': "/usr/bin/firefox",
        'firefox.cli.args': ['--webdriver-loglevel=ERROR', '--local-storage-path=/tmp/phantom_' + Math.random()]
 	},

	{ 
        'browserName': 'chrome',
        'firefox.binary': "/usr/bin/chrome",
        'firefox.cli.args': ['--webdriver-loglevel=ERROR', '--local-storage-path=/tmp/phantom_' + Math.random()]
 	},

	{
        'browserName': 'phantomjs',
        'phantomjs.binary.path': require('phantomjs').path,
        'phantomjs.cli.args': ['--webdriver-loglevel=ERROR', '--local-storage-path=/tmp/phantom_' + Math.random()]
	}   

	],
maxSessions: 1,

  // Setup the report before any tests start
  beforeLaunch: function() {
    return new Promise(function(resolve){
      reporter.beforeLaunch(resolve);
    });
  },

  // Assign the test reporter to each running instance
  onPrepare: function() {
    jasmine.getEnv().addReporter(reporter);
  },

  // Close the report after all tests finish
  afterLaunch: function(exitCode) {
    return new Promise(function(resolve){
      reporter.afterLaunch(resolve.bind(this, exitCode));
    });
  }

}

```
