### ISSUE TITLE
Work Item Details Slide-in Animation too slow

### ISSUE THREAD

**Issue by tsmaeder** [fabric8io/fabric8-planner#306]
How to reproduce:
1. Go to the "Work" tab
2. Observe: you see a list of work items
3. Click on a work item
4. Observe: a details view of the work item slides in from the right. The slide-in animation takes about 0.8 seconds to complete. That is enough time that it feels like I have to wait for it.

My expectation would be that the animation is no longer than 0.3 secs.

Fedory 24, Firefox 49.0

**Comment by nimishamukherjee** [comment]
@almighty/uxd could you please review and recommend on this issue.

**Comment by mindreeper2420** [comment]
@tsmaeder @nimishamukherjee We have not worked on any animations to this point so no recommendations can be given, other than to follow whatever timing can be found within PatternFly's code. @almighty/uxd
