### ISSUE TITLE
WorkItem Id shows as random number 

### ISSUE THREAD

**Issue by almightytest** [fabric8io/fabric8-planner#310]
WorkItem Id shows as random number 
I come across a interesting issue, while running automation.The WorkItem Id shows as random number when we hit enter and save title.Well this is not reproduced without automation. I will update issue once its reproduced without automation,
screenshot attached.
![screenshot from 2016-11-11 13-54-11](https://cloud.githubusercontent.com/assets/23330096/20217546/49877d6c-a846-11e6-910d-f17014e5fc78.png)
![screenshot from 2016-11-11 18-01-47](https://cloud.githubusercontent.com/assets/23330096/20217547/4988cff0-a846-11e6-8ff6-7abe9ed45925.png)

**Comment by joshuawilson** [comment]
@naina-verma @ldimaggi Where you able to reproduce this?

**Comment by naina-verma** [comment]
@joshuawilson , yes its easy to reproduce by automation.
