### ISSUE TITLE
Investigate PhantomJS failures that are not seen with Chrome/Firefox - Replace PhantomJS with (headless/Xvfb) Chrome/Firefox in functional tests

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#319]
See:  https://github.com/almighty/almighty-ui/pull/315#issuecomment-261056870

We are seeing some issues with PhantomJS not being able to access UI elements that can be accessed by Chrome/Firefox. So far, we have been able to work around these issues.

**Comment by ldimaggi** [comment]
See: #315 (comment)

Comments on the tests failing in the latest commit.

Overall, it looks like the workitem type pulldown implemented in the work item detail page does not behave as expected when the tests are run with PhantomJS in that the tests are not able to locate/access the values in the pulldown. The tests so not encounter these problems when run with FireFox or Chrome. I will open a separate task in github for this problem to be investigated.

In the meantime, we can implement the following workarounds to get the tests running - the updated statements replace the commented-out code:

**In displayAndUpdateWorkItemDetails.spec**

The expected test (the string representation of the work item type) is correctly included in the html, but the test cannot find the corresponding element in the UI when the test is run with PhantomJS:

```
      /* Verify the name display of workitem types are correct  - phone*/
           it('Verify the name display of workitem types are correct ', function() {
              var workItemTitle = "The test workitem title";
              var workItemUpdatedTitle = "The test workitem title - UPDATED";
              page.clickWorkItemQuickAdd();
              page.typeQuickAddWorkItemTitle(workItemTitle);
              page.clickQuickAddSave().then(function() {
                expect(page.workItemTitle(page.firstWorkItem)).toBe(workItemTitle);
                expect(page.workItemTitle(page.firstWorkItem)).toBe(workItemTitle);
                page.workItemViewId(page.workItemByTitle(workItemTitle)).getText().then(function (text) {
                  var detailPage = page.clickWorkItemTitle(page.firstWorkItem, text);
                  detailPage.clickworkItemDetailTypeIcon();
                  var wi_types = ["userstory", "valueproposition", "fundamental","experience","feature","bug"];
                  for(var i=0;i<wi_types.length;i++){
                 // expect(detailPage.WorkItemTypeDropDownList().get(i).getText()).toBe(wi_types[i]);
                  expect(detailPage.workItemTypeDropDownListString(wi_types[i]).getAttribute('innerHTML')).toContain(wi_types[i]);
                  }
                  detailPage.clickWorkItemDetailCloseButton();
                });

              });

      });
```

In this test method, it is not necessary to click on the workitem types pulldown as the work item type is correctly displayed when the newly created work item's detail page is opened. The value of the work item type cannot be found using the CSS selector method (detailUserstroyIcon) in this test method. A new test method (detailUserstroyIcon2) was created to access the workitem type of the newly created workitem.

```
/*Verfify on selecting workitem it should display in list and detail view both pages - Desktop  */
 it('Verfify on selecting workitem it should display in list and detail view both pages -Desktop ', function() {
    testSupport.setBrowserMode('desktop');
    var workItemTitle = "The test workitem title";
    var workItemUpdatedTitle = "The test workitem title - UPDATED";
    page.clickWorkItemQuickAdd();
    page.typeQuickAddWorkItemTitle(workItemTitle);
    page.clickQuickAddSave().then(function() {
       page.workItemViewId(page.workItemByTitle(workItemTitle)).getText().then(function (text) {
        var detailPage = page.clickWorkItemTitle(page.firstWorkItem, text);
//        detailPage.clickworkItemDetailTypeIcon();
//        detailPage.clickWorkItemTypeDropDownList(0).click();
//        detailPage.clickWorkItemDetailCloseButton();
//        expect(detailPage.detailUserstroyIcon().isPresent()).toBeTruthy();
        expect(detailPage.detailUserstroyIcon2("fa-bookmark").isPresent()).toBeTruthy();
     });
    });

```

**In work-item-detail.page**

This new test support method was added. This method enables tests to locate a workitem type in the workitem type pulldown based on the name string of the workitem type:

```

  workItemTypeDropDownListString:  {
    value: function (typeString)
    { 
      return element(by.xpath("//*[@id='wi-detail-form']//li[.//text()[contains(.,'" + typeString + "')]]")); 
    }
  },
```

And, this new test was also added. This method enables the test to verify the presence of a workitem type icon in the context of a workitem's detail page.

```
  detailUserstroyIcon2:   {
    value: function (classString)
    {
      return element(by.xpath("//*[@id='wi-detail-form'][.//*[contains(@class, '" + classString + "')]]")); }
  },

```

**Comment by ldimaggi** [comment]
PhantomJS is also unable to recognize when the "move" dropdown is active - this works cleanly on firefox and chrome

```
browser.wait(until.elementToBeClickable(page.workItemMovePulldownDown(page.workItemMovePulldown)), waitTime);
page.clickWorkItemMovePulldownDown(page.workItemMovePulldown);
```

**Comment by ldimaggi** [comment]
And - another problem - Chrome/Firefox are able to recognize/manipulate the workitem filtering pulldown, but PhantomJS is not able to do this.

**Comment by ldimaggi** [comment]
PhantomJS is also showing fragility issues related to errors - see:  https://github.com/fabric8io/fabric8-planner/issues/857

**Comment by ldimaggi** [comment]
And - PhantomJS is unable to recognize UI elements on this page:

http://console.prod-preview.openshift.io/public

**Comment by ldimaggi** [comment]
It looks like many other people are having blocking issues using PhantomJS and dropdown boxes:

https://www.google.com/search?q=jasmine+dropdown&oq=jasmine+dropdown&gs_l=serp.3..0i30k1.6872.9610.0.9935.8.8.0.0.0.0.311.920.0j1j2j1.4.0....0...1c.1.64.serp..5.3.674...0j0i7i30k1j0i7i10i30k1j0i8i7i30k1.OYqnOoTF39o

**Comment by ldimaggi** [comment]
Another instance of problems with PhantomJS and dropdown boxes:

https://github.com/naina-verma/fabric8-planner/tree/adding-linktest

**Comment by naina-verma** [comment]
Hi Len,

I have started working on this issue. We need to modify few things into our Dockerfile.builder and run_functional_test.sh 
- Installing Chrome on docker container
- Installing XVFB on docker container 
- Setting environment variable for screen display 
RUN /usr/bin/Xvfb :99 -ac -screen 0 1024x768x24 &
ENV DISPLAY=:99
- And run tests with xvbf 
xvfb-run node_modules/protractor/bin/protractor protractor.config.js

This entire thing works fine on a system but with docker its facing  some trouble will update you about docker status !
