### ISSUE TITLE
Bug: 'Work' is not highlighted as active tab when site loads.

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#337]
As the 'Work' page is the default screen for when a user visits demo.almighty.io, it should be highlighted. Currently, it is not highlighted unless the user visits another page and then returns to the 'Work' page.

Current Behavior on Initial Load:
![screen shot 2016-11-22 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/4032718/20537369/e787e9e4-b0ba-11e6-93cd-22f246986424.png)

Expected Behavior:
![screen shot 2016-11-22 at 1 53 02 pm](https://cloud.githubusercontent.com/assets/4032718/20537400/03afa99a-b0bb-11e6-9c3c-4353ba376ebf.png)

Note: the Active state should have the text as #363636, not white.

**Comment by sanbornsen** [comment]
@mindreeper2420 header section will be removed from planner. Can you close this issue?

**Comment by mindreeper2420** [comment]
@sanbornsen - can you link this to the Issue that removes the header section? I know of no Issue that removes the headers.
