### ISSUE TITLE
Support Order of Execution

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#355]
As a part of the User Story "Order of Execution for the Work Item List" (https://github.com/almighty/almighty-core/issues/318), the UI should support design to change the order of workitems.

NOTE: This should be without drag-and-drop

**Comment by joshuawilson** [comment]
@DhritiShikhar why did you create this issue? Why did you assign it to the next sprint before we voted on the stories of the that sprint?

**Comment by DhritiShikhar** [comment]
@joshuawilson i removed the milestone. sorry for the confusion.
