### ISSUE TITLE
Bug: Newly Added Work Item Doesn't Show In List

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#372]
When I attempt to add a work item to the list, it does not appear. I am presented with the following information in my console:

<img width="1920" alt="screen shot 2016-11-29 at 8 28 08 pm" src="https://cloud.githubusercontent.com/assets/4032718/20736100/6e5f6d0e-b672-11e6-8ab0-2a9412b8a59a.png">

**Comment by joshuawilson** [comment]
I think this has to do with the Order of the list and the lack of pagination.

**Comment by mindreeper2420** [comment]
Have restrictions already been added to the list size?

**Comment by joshuawilson** [comment]
From the beginning the backend only returns a limited set of the data, if I understand correctly.

**Comment by mindreeper2420** [comment]
Gotcha, makes sense then. Wasn't sure what the logger message was all about, even after looking at it.

**Comment by sanbornsen** [comment]
@joshuawilson @mindreeper2420 close this issue if we are gonna resolve it with order related work.

**Comment by joshuawilson** [comment]
@sanbornsen I would prefer to not close a bug because we know we will fix it eventually. It should stay open as long as it is a bug. That allows others to find this bug some place to see that we know it exists and is being worked.
