### ISSUE TITLE
Closed button should be replaced with toggle

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#379]
Closed button should be replaced with toggle,because when you click on close it hides all the linking div.
But still (close button) shows up, which gives an impression you can close it further.
![screenshot from 2016-11-30 15-41-19](https://cloud.githubusercontent.com/assets/19172870/20748320/b5f12b8e-b713-11e6-8273-3b09529b66fa.jpg)

**Comment by joshuawilson** [comment]
@almighty/uxd can you please look at this issue and advise.
