### ISSUE TITLE
Create a Dialog for Creating a Project

### ISSUE THREAD

**Issue by tsmaeder** [fabric8io/fabric8-planner#392]

**Comment by Mgranfie** [comment]
InVision Link:
https://redhat.invisionapp.com/share/UC96TAOWH

JIRA STORY:
https://patternfly.atlassian.net/browse/RHUAP-504

**Comment by Mgranfie** [comment]
@nimishamukherjee @joshuawilson I mocked up the concept for create full new work item and posted to InVision.

Feel free to comment and lmk if you want to set up time to review. I know this was underway, so wanted to get out at least a high level concept to you.

https://redhat.invisionapp.com/share/Y39KFTAE7

**Comment by joshuawilson** [comment]
@Mgranfie I think your last comment was added to the wrong issue. Can you please add it to #391
