### ISSUE TITLE
Create Org Menu to List Projects

### ISSUE THREAD

**Issue by tsmaeder** [fabric8io/fabric8-planner#393]

**Comment by Mgranfie** [comment]
@tsmaeder @joshuawilson Am not able to edit the story... attaching the link to the InVision wireframes.

New Project:
https://redhat.invisionapp.com/share/UC96TAOWH

**Comment by SMahil** [comment]
HTML for Org Menu : #444

**Comment by SMahil** [comment]
@Mgranfie Please provide the mobile view design for Menu. Right Now Menu is breaking on mobile view

<img width="345" alt="screen shot 2016-12-07 at 3 13 17 pm" src="https://cloud.githubusercontent.com/assets/10396359/20962544/ba510c68-bc8f-11e6-95fc-b3a4eeda2083.png">

**Comment by joshuawilson** [comment]
The menu / navigation system is being rewritten in the new fabric ui. You can still create the drop down and it will get converted to the new system.
