### ISSUE TITLE
User should not be able to create duplicate/redundant links

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#430]
See attached screenshot - the user should not be able to create multiple duplicate links:

![screenshot from 2016-12-05 10-17-48](https://cloud.githubusercontent.com/assets/642621/20890318/66c4f1a2-bad4-11e6-905a-1554d690df65.png)

**Comment by kwk** [comment]
Thank you for reporting this issue. I will address it.

**Comment by nimishamukherjee** [comment]
@ldimaggi / @kwk this has been fixed on the UI. Anything needs to be done on core?

**Comment by sanbornsen** [comment]
@kwk is the backend handling this? From UI side we are not allowing user to add duplicate link.

**Comment by Mgranfie** [comment]
As this is not a scenario that we mapped out in the UI, one question I have
is how this event is being realized in the UI and communicated to the user?

A few ideas come to mind quickly, but would need to be vetted.

* Don't show links that already exist in the drop down of links
* Show the links, but disable them
* Show the links, disable them and add a qualifier that indicates the link
is already linked. We could even go so far as to highlight the link below
and bring it into focus if the user hovers or selects it.
* Show a dialog stating that "You already have created the same link with
this item... - OK" (not the best wording but the idea :)

I am not sure where the discussions are with this and what decisions might
have already been made, but Sudipta if you can bring me up to date and we
can look at solutions together, that would be great.

Thanks,
Monica
