### ISSUE TITLE
Error message is not provided to user if an attempt is made to create an invalid link

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#431]
If a user attempts to create an invalid link, for example, a link that indicates that a workitem of type userstory is blocked by another work item of type userstory, the UI prevents ths user from creating this link, but the user is not provided with an error message that indicates why the link is not created when the user clicks on the link button. From user's perspective, the link button simply fails to function.

**Comment by sanbornsen** [comment]
We don't allow user to search for invalid work item to link. So this error will never occur anymore. Any item in the search suggestion is valid for the link.
