### ISSUE TITLE
Users should not be able to create self-referencing links

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#432]
See attached screenshot - users should not be able to create a link from a workitem to itself.

![screenshot from 2016-12-05 10-30-20](https://cloud.githubusercontent.com/assets/642621/20890708/d856a8a0-bad5-11e6-9452-4ae1cbbdcfb3.png)

**Comment by Mgranfie** [comment]
That is correct, at this time, at least.

**Comment by nimishamukherjee** [comment]
@ldimaggi, @naina-verma  this has been fixed. Please review on http://demo.almighty.io

**Comment by naina-verma** [comment]
@ldimaggi , @nimishamukherjee  verified , it works fine !
