### ISSUE TITLE
Search field in workitems links requires 2-chars in order to perform a search

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#436]
Is this intentional? The search field does not begin to perform searches until 2 characters (even if one of the characters is a space) are entered.

**Comment by nimishamukherjee** [comment]
@sanbornsen can you confirm this?

**Comment by sanbornsen** [comment]
Less than three characters make the search operation very expensive in backend. This is a common pattern to follow.
@fabric8io/uxd can you confirm?

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
