### ISSUE TITLE
Search field in work item links is limited to [a-z][A-Z][0-9]

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#437]
The searching does not seem to recognize these characters:  !@#$%^&*(){}[], etc.

**Comment by Mgranfie** [comment]
@sanbornsen @michaelkleinhenz We can look at this tomorrow in our UX Meet up. Sudipta not sure if you are available now to review.. if so ping me on Hipchat...

**Comment by ldimaggi** [comment]
See:  https://openshift.io/openshiftio/openshiftio/plan/detail/1035
