### ISSUE TITLE
WorkItem Links does not show up on when direct detail link is hit

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-planner#438]
## Steps to reproduce

* Go to http://demo.almighty.io/work-item-list/detail/346
* No links are shown
* Select another WorkItem from the List
* Use back button to go back to the first WorkItem
* 64 links are shown (64 links are actually correct number according to DB)

Demo: https://youtu.be/sjAUbtMVrUM

**Comment by joshuawilson** [comment]
@sanbornsen can you please take a look at this.

**Comment by debloper** [comment]
Can't reproduce.

**Comment by sanbornsen** [comment]
I think this issue is not there anymore. Got resolved with last set of update for linking.

**Comment by sanbornsen** [comment]
@aslakknutsen can you verify and close the issue?

**Comment by nimishamukherjee** [comment]
Closing as the issue has been fixed.
