### ISSUE TITLE
WorkItem Link type pull down broken style in Firefox

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-planner#439]
![screenshot from 2016-12-06 00-40-21](https://cloud.githubusercontent.com/assets/132158/20907197/104ed328-bb4d-11e6-9c26-d0e754de5fa9.png)

**Comment by nimishamukherjee** [comment]
![firefox_wilink_dropdown](https://cloud.githubusercontent.com/assets/1892722/22051422/07952ee2-dd69-11e6-9e3a-24388635274e.png)

The work item link drop down has been fixed.
