### ISSUE TITLE
UI Header is not responsive in mobile view

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#496]
UI Header is not responsive in mobile view
The header items are not aligned as per mobile responsive view. screenshot attached
![screenshot from 2016-12-12 11-51-43](https://cloud.githubusercontent.com/assets/19172870/21089869/a5b34354-c061-11e6-8db8-635d5ebb6e7a.png)

**Comment by SMahil** [comment]
@Mgranfie Can you confirm the UX for mobile header

**Comment by nimishamukherjee** [comment]
Closing this issue as this is no longer relevant to planner.
