### ISSUE TITLE
Inappropriate representation of time "Created at" 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#507]
Inappropriate representation of time "Created at" 
![screenshot from 2016-12-13 16-51-45](https://cloud.githubusercontent.com/assets/19172870/21139106/5c8ef82a-c157-11e6-990b-aa03c834e75a.png)
![screenshot from 2016-12-13 16-51-58](https://cloud.githubusercontent.com/assets/19172870/21139107/5c960020-c157-11e6-9757-85fb2e29447b.png)

**Comment by naina-verma** [comment]
Ref #https://github.com/almighty/almighty-core/issues/579

**Comment by aslakknutsen** [comment]
The first one is due to missing data in the backend. At some point our dates got screwed and they all came out as 01.01.0001. What's wrong with the second one?

**Comment by nimishamukherjee** [comment]
@naina-verma we need to receive the final UX around display of work item creation. 
For now, we have created a Git Hub like experience. If you hover over the text, you get to see that date.
As Aslak mentioned we get "2016 years ago" for some of the work items.

**Comment by sanbornsen** [comment]
This seems fixed. @naina-verma please verify and close the issue.

**Comment by naina-verma** [comment]
@sanbornsen , Verified !
