### ISSUE TITLE
Bug: Work Item Linking Navigation Menu Breaks in Mobile View

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#512]
In Work Item Linking, Navigation on detail page is breaking in mobile view because of long texts.

<img width="322" alt="screen shot 2016-12-14 at 10 07 16 am" src="https://cloud.githubusercontent.com/assets/10396359/21169780/513d7dd2-c1e5-11e6-8ae9-24b6baa55c21.png">

**Comment by SMahil** [comment]
@vikram-raj @joshuawilson @sanbornsen @nimishamukherjee Can you please verify the navigation heading if we are having this much big texts only

**Comment by Mgranfie** [comment]
There were only originally 3 sections here. Was customization a requirement
and do we need to revisit this design to provide an overflow use case
solution?

Thanks,
Monica

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz do we need a UI to add work item link type? This impacts how many tabs get displayed. Currently they are added into the DB manually.
ccing @Mgranfie
