### ISSUE TITLE
User has small margin of error to position cursor in order to be able to enter workitem description

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#562]
See the referenced screencast - the user must precisely position the cursor into a very small area on the screen in order to be able to type in a new work item description - this is in the new work item creation dialog.

https://dl.dropboxusercontent.com/u/12067552/Screencasts/new_workitem_position_cursor.webm

**Comment by debloper** [comment]
What's the UX suggestion to resolve this?
