### ISSUE TITLE
"undefined" shows up for description , detail view page :: Firefox

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#566]
"undefined" shows up for description , detail view page
- When open new wi dialogue, it shows "undefined" for description on edit  
![screenshot from 2016-12-22 12-41-39](https://cloud.githubusercontent.com/assets/19172870/21417976/376bf608-c844-11e6-820a-356619ba8a9e.png)

**Comment by nimishamukherjee** [comment]
@naina-verma this has been fixed. Please verify.

**Comment by naina-verma** [comment]
Verified !
