### ISSUE TITLE
"x" cancel button for title,not clearing the title field  unless the work item is not created 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#570]
"x" cancel for title for new dialog WI should not shows up
- while creating new wi from (+) , new dialog wi , we should not shows up "x" button for title.
When we are creating title for the first time.
- it should shows up only on edit.
Video https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COSGlxUkRLclowdkU/view?usp=sharing

**Comment by naina-verma** [comment]
@almighty/uxd  please check if this behavior can be the part of UI!

**Comment by mindreeper2420** [comment]
@naina-verma I'm a bit confused by what you are asking, but the 'X' should be there as the close/cancel/clear mechanism.

**Comment by naina-verma** [comment]
@mindreeper2420 ,
I think this video can explain much about what i am asking : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COQ2o0RUF6UlQzOXM/view?usp=sharing
It can be bug from UI side implementation.

Well, "x" is not clearing the title field  unless the work item is not created !
@sanbornsen  please look into it!
