### ISSUE TITLE
No Validation for invalid definition On changing WIT 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#587]
No Validation for invalid definition On changing WIT 

Scenario: 
Right now there is support for Planner item to Planner item definition and Bug to Planner Item.
Say for example user has created one work item as planner and linked with planner item. What if , when user try to change the WIT to user story or feature.
Expected : It should throw validation error from API and UI , that definition type is not supported.
Actual : Changes the WIT without any warning to incorrect WIT and definition.

**Comment by sanbornsen** [comment]
@mindreeper2420 @Mgranfie please comment on this.

**Comment by sanbornsen** [comment]
Do not consider the parent child relationship of types on this.
