### ISSUE TITLE
Tittle display height should be little increase , words like "y,g" shows up incomplete 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#604]
Tittle display height should be little increase , words like "y,g" shows up incomplete 
![screenshot from 2016-12-28 13-10-27](https://cloud.githubusercontent.com/assets/19172870/21516540/320e347c-ccff-11e6-894d-3bba30f1488c.png)

**Comment by nimishamukherjee** [comment]
@naina-verma can you verify? PR #625 has been merged.

**Comment by naina-verma** [comment]
@nimishamukherjee  Verified !
