### ISSUE TITLE
In a certain size > mid? I can scroll horizontally on the ListView

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-planner#61]
![screenshot from 2016-09-06 02-21-54](https://cloud.githubusercontent.com/assets/132158/18258614/0a0a20e6-73d9-11e6-881a-ea53b662f2cc.png)

**Comment by sanbornsen** [comment]
This issue is resolved at PR - https://github.com/almighty/almighty-ui/pull/62
I'd like some CSS expert to review it, because i am not very sure if this is the correct way to do things.

**Comment by joshuawilson** [comment]
@aslakknutsen I think this is a simple mistake with CSS. I expect that once we get the new designs it will get resolved.

**Comment by joshuawilson** [comment]
@sanbornsen @aslakknutsen is this still an issue?

**Comment by sanbornsen** [comment]
@aslakknutsen I don't see this anymore? Shall we close?
