### ISSUE TITLE
Time not displayed for WI

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#610]
Time not displayed for WI ,only date displayed 
The created date and time should be displayed on UI , at present date is displayed.
But the core has stored time stamp also 
`select * from work_items where id='441';
          created_at           |          updated_at           | deleted_at | id  |       type       | version |                                                                         
                                                                   fields                                                                                                                
                            |                      tsv                       
 2016-12-01 09:20:42.694238+00 | 2016-12-27 08:57:17.831907+00 |            | 441 | system.userstory |       1 | {"system.state": "new", "system.title": "automation title", "system.crea
tor": "4b8f94b5-ad89-4725-b5e5-41d6bb77df1b", "system.assignees": ["9468638d-efb0-47aa-bdeb-85202b5422a3"], "system.iteration": null, "system.description": "automation description", "sy
stem.remote_item_id": null} | '441':1A 'autom':2B,4C 'descript':5C 'titl':3B
(1 row)`

![screenshot from 2017-01-02 15-18-56](https://cloud.githubusercontent.com/assets/19172870/21587153/0834015a-d0ff-11e6-891e-61f10528cd91.png)

**Comment by vikram-raj** [comment]
Please refer to this mock up https://redhat.invisionapp.com/share/2F9N0A7WN#/screens/211446631

**Comment by naina-verma** [comment]
@vikram-raj , thanks for pointing to invision .

**Comment by mindreeper2420** [comment]
@naina-verma The visuals do not have a timestamp, so the time is not displayed. Even though Core provides it, we do not show it.

Please review this [document](https://docs.google.com/a/redhat.com/document/d/1DuBgTaX_U_OGcmzwUHVLpkuRhGsVCVFpBX6bgKm2d4s/edit?usp=sharing) for created date/time verbiage.

**Comment by ldimaggi** [comment]
I vote for also showing th time created, in addition to just the date. It's very common for people to want to track the time created, updated, etc. as multiple changes/state changes can happen during the same day. Think of how we use JIRA!  ;-)

Thx!,
Len

**Comment by mindreeper2420** [comment]
As the date is not in this iteration of the visual design, I would leave it out for now and request an iteration with the full date/timestamp in there. The design will have to be updated in order to fit that information properly.

**Comment by Mgranfie** [comment]
I am in agreement of going out with what we have. Is the "Time" necessary to a critical path workflow in using the product for summit?
