### ISSUE TITLE
Item linking search results not changed dynamically ,onchanging  linktype

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#633]
Item linking search results not changed dynamically ,onchanging  linktype

- select tests type item linking
- choose search PI result 
- Change type of item linking 
the search result should be changed once the type is change .
Video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COeEcxMmdNOVNUUVk/view?usp=sharing

**Comment by nimishamukherjee** [comment]
@naina-verma please verify on http://demo.almighty.io

**Comment by naina-verma** [comment]
@nimishamukherjee , 
Please look into video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COc2Y4SDZ1RUwzVms/view?usp=sharing
Its partially fixed . In video you will see that one changing tabs with invalid wi-id , its not clearing the fields.

**Comment by nimishamukherjee** [comment]
@naina-verma created #800 for the above issue - want to keep the PRs small.
