### ISSUE TITLE
Remove menu to change work item's type

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#635]
~~With respect to~~ With respect to https://github.com/almighty/almighty-core/pull/595#issuecomment-270675818 the menu to change a work item's type must be removed:
 
![33f15a8c-c5c8-11e6-8a7b-e11eb296e99f](https://cloud.githubusercontent.com/assets/193408/21686784/d717829e-d366-11e6-9641-b61cece54c99.png)

It can be found on the work item's details page.

**Comment by nimishamukherjee** [comment]
PR merged hence closing this issue.
