### ISSUE TITLE
Kebab Menu Implementation on Board view

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#638]
Kebab Menu should open in Board View and as a user I should able to open delete and move the WI as we have in List View

**Comment by Mgranfie** [comment]
Hi Melody,

I will make a story for this on the UX side, so we can coordinate and
revisit the menus on the work item in the boards and the backlog list.

-Monica

**Comment by SMahil** [comment]
@Mgranfie Any update on this?

**Comment by Mgranfie** [comment]
Hi Sukhvir,

Am sorry for the delay as I was in meetings in Brno. Am back today. We
found out late this week that Melody is off for last week and next week. So
I will take a look at this today and get something posted for you that we
can then discuss so we can get you unblocked.

Thanks
Monica
