### ISSUE TITLE
In the detailed Workitem creation dialog, a status of "Created" is always displayed - even if the workitem is not yet created

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#643]
See attached screenshot:

![screenshot from 2017-01-06 12-48-08](https://cloud.githubusercontent.com/assets/642621/21727648/5064e340-d410-11e6-8030-47655a9dce22.png)

**Comment by nimishamukherjee** [comment]
@fabric8io/uxd confirming the Created behaviour - we will not display the "Created" text during work item creation via the dialogue box.

**Comment by nimishamukherjee** [comment]
@ldimaggi / @naina-verma please verify the fix on demo.almighty.

**Comment by naina-verma** [comment]
@nimishamukherjee , Fix works fine !
