### ISSUE TITLE
Update an Iteration [7]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#647]
_From @michaelkleinhenz on October 27, 2016 15:9_

# Description

As a user, I can update an iteration for a space and change title and start and end dates. 

# Functional Acceptance Criteria
1. The user can select an iteration from a list of all iterations of the current space. The list order is undefined for this story.
1. The user can update an iteration from a dialog that opens when an iteration is selected from the list.
2. The user can change the title (alphanumeric value), the start date (date) and the end date (date).
3. It is not possible to update an iteration with an empty title.

# Non-functional Acceptance Criteria
1. The "list/update iteration" view is easily accessible from anywhere in the system UI.

# Dependencies
1. Userstory #409 
2. Userstory #411 
3. Userstory #412 

[Visual Design](https://redhat.invisionapp.com/share/KA9CAYL7M#/screens)

_Copied from original issue: almighty/almighty-core#410_

**Comment by michaelkleinhenz** [comment]
_From @qodfathr on October 30, 2016 17:44_

Logic tied to the current date is generally not worth the effort. I should be able to set the start date to a date preceding today. Let's say I forgot to create an iteration for this month -- why are you having the system deny me creating it? A warning that I can turn off may be okay, but this shouldn't be a hard-coded rule. [e.g. QuickBooks warns me when I make accounting entries which are more than 6 months old -- just to be sure I didn't type the year wrong. But it does let me put these entries into the system.]

**Comment by michaelkleinhenz** [comment]
@qodfathr ok, updated the story.

**Comment by michaelkleinhenz** [comment]
_From @ldimaggi on October 31, 2016 18:41_

Will there be a history/audit trail for updates made to the start/end dates?

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on October 31, 2016 19:21_

Would this be part of the larger log/audit file?... I am not sure if this
would be something the user would want to see as part of the experience?...

**Comment by michaelkleinhenz** [comment]
_From @qodfathr on November 2, 2016 12:58_

While I'm in favor of auditing almost everything, auditing changes to iteration dates strikes me as something that almost no one would care about. (Yes, I can come up with some use cases. But I believe they very rarely happen.) If we can capture this data, let's do so, but let's not work on any UX around it until we've got more data on usage (how often does it happen) and need (someone wants to review the data).

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on November 2, 2016 17:47_

+1 on not auditing the Iteration dates right now.

**Comment by michaelkleinhenz** [comment]
@Mgranfie @qodfathr yes, not part here, because this has a much bigger scope. Logging/auditing is an epic of its own. There were talks in Westford about being able to roll the system back to any point in time, etc..this is much bigger than what can be done in this story.

**Comment by michaelkleinhenz** [comment]
_From @qodfathr on November 4, 2016 15:28_

@michaelkleinhenz right, a 'true, 100% rollback' would need something like this. Maybe a 'mostly true, 99% rollback' will suffice. :) Thanks for the reminder on this subtlety.

**Comment by michaelkleinhenz** [comment]
Important addition: we might need some way to select or view an iteration from a list of iterations. How are they ordered in that list? What iterations are displayed there? This is needed in the story.

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on November 8, 2016 13:49_

Michael,

In the current designs we have a list of iterations, right now they are
listed by date, start date being the identifier.

Let me know if this makes sense.

Thanks,
Monica

**Comment by michaelkleinhenz** [comment]
_From @maxandersen on November 8, 2016 13:52_

Since date are optionals sorting by date does not make sense IMO.

It should be an ordered sequenced list.

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on November 8, 2016 14:34_

Proposing to go for alphabetical, until and even if we have dates...

**Comment by michaelkleinhenz** [comment]
As alphabetical would only be a temporary solution until we defined something better, can't we just go for "unsorted" for now? Thats what we've done on the worklist..just leaving out any sorting and display the items as they are in the data(base).

**Comment by michaelkleinhenz** [comment]
_From @qodfathr on November 9, 2016 16:15_

Iterations are ordered. It is a _list_ of data (actually, it's hierarchical -- remember, iteration is a path data type) -- and lists are, by definition, ordered (otherwise we'd call them a bag).

So if I type in

Iteration 1
Iteration B
Iteration III

then that's the order of the iterations. This is super-critical for the UX to have any degree of sanity.

As a lower priority feature, I should be able to drag/drop reorder and reparent them.

e.g.

Release 1
&nbsp;&nbsp;Sprint 1
&nbsp;&nbsp;Sprint 2
Release 2
&nbsp;&nbsp;Sprint X
&nbsp;&nbsp;Sprint Y

I should be able to drag Sprint X to somewhere else, such as:

Release 1
&nbsp;&nbsp;Sprint 1
&nbsp;&nbsp;Sprint 2
&nbsp;&nbsp;Sprint X
Release 2
&nbsp;&nbsp;Sprint Y

or even

Release 1
&nbsp;&nbsp;Sprint 1
&nbsp;&nbsp;&nbsp;&nbsp;Sprint X
&nbsp;&nbsp;Sprint 2
Release 2
&nbsp;&nbsp;Sprint Y

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on November 9, 2016 20:55_

Todd,

Based on your examples, are we limiting the names of the Iterations and
Sprints to "Iteration #", "Sprint #" and "Release #" then?

This as a requirement. These are auto generated with a numeric appendage?

Thanks,
Monica

**Comment by michaelkleinhenz** [comment]
_From @qodfathr on November 9, 2016 21:55_

@Mgranfie No, they can have any name you want. No autogeneration of any kind. (Although we should consider some auto generation for the future. Often I will want "Sprint n, Sprint n+1, Sprint n+2..." auto generated for some value of n, likely also with dates (e.g., "every two weeks starting with jan 12, 2017").

But that's not for today. We can discuss in January.

The initial development methodology selection should be able to prepopulate the project with a list of initial recommended iterations. (e.g., the Scrum methodology might give you "Sprint 1," "Sprint 2," ... "Sprint 6" as a reasonable start. The user can then modify or delete these, of course.)

**Comment by michaelkleinhenz** [comment]
_From @Essjaysee on December 20, 2016 21:55_

@joshuawilson @aslakknutsen @maxandersen @michaelkleinhenz  Wireframes for iterations: https://redhat.invisionapp.com/share/KA9CAYL7M

**Comment by pranavgore09** [comment]
Workflow for Iteration -
* Create an iteration with just name and description (No selection of dates at that point).
* The newly created iteration will be listed under the Future accordion.
* Find two option for each iteration Edit and Start.
* At this point clicking on edit will only let the user update the title and the description.
* Clicking on Start should open a modal to select start and end date and save.
* The UI will sort the iterations as Current, Future, and Past based on the date range.
  An iteration without a date will go into Future
  Based on the start date and end date the iteration will be re positioned.
    * If start date <= current date <= end date - Present
    * If start date > current date - Future
    * If end date < current date - Past
* Now on in the option there will be only two options Edit and Close
* Now edit should let the user edit the start date end date as well along with title and description

**Comment by michaelvirgil** [comment]
@fabric8io/uxd - SJ can you connect with @pranavgore09 to walk-thru the interactions?

**Comment by Essjaysee** [comment]
Hi @pranavgore09.  I like how you paraphrased the workflow!  Just a couple of comments to clarify:

- The user should be able to add dates, via the Edit dialog, to iterations that are in the Future list.
- Iterations are sorted this way: current iterations are those that the user has started via the Start dialog, future iterations are created (with or without a date) but haven't been started yet, past iterations have been closed via the Close dialog.  Date ranges aren't used to sort them into these categories.

**Comment by pranavgore09** [comment]
@Essjaysee Thanks fro inputs. Actually workflow is jotted down by @sanbornsen :smiley: 


@sanbornsen : So according to this input
  1. we can not use value of `start_date` to decide the category of Iteration.
  2. Need to update `Edit` dialog box to have dates in it.


@aslakknutsen : Does this imply we should maintain a `state` of the Iteration ?
Like, `start`, `future`, `past` can be possible values of the Iteration. `Default=Future`
UI will use `patch` APi to change the state. (No dedicated APIs to start/end iteration)

**Comment by aslakknutsen** [comment]
@pranavgore09 I think the states we've been talking about are simply 'Active' or not.

**Comment by pranavgore09** [comment]
@aslakknutsen yeah thanks

If we consider `isActive` is a `*bool` on Iteration (on create `isActive=nil`) then - 
* If iteration.isActive == true ---> Current
* If iteration.isActive == false --->  Past
* If iteration.isActive == nil --->  Future

**Comment by michaelvirgil** [comment]
@pranavgore09 @aslakknutsen 

I think of the iteration.isActive as follows:
- Active (currently executing) or not
- Future and past etc. is determined by start/end dates

Until the iteration milestone dates are set - the iteration is just a tentatively planned list of work items.

**Comment by aslakknutsen** [comment]
@michaelvirgil @pranavgore09 At this point, do we care if 'it's currently executing'. I thought the 'active'/'enabled'/'visible' was more a flag to 'hide' it from the main list.

e.g. I can see:

* Sprint 2
* Sprint 3
* Sprint 4

Our current sprint is Sprint 2 and the one we're working on. I can't immediately see Sprint 1 because it's set to 'active' false but can be found under the 'all/hidden/ended' iterations submenu..  ?

**Comment by pranavgore09** [comment]
@michaelvirgil yes, we can verify `dates` to calculate future and past sections but I think [wireframes](https://redhat.invisionapp.com/share/KA9CAYL7M) are not designed with this thought, can you please confirm @Essjaysee - Should dates be used to calculate Future/Past for an iteration.
And If we go by dates, will `start` and `end` buttons be useful to user ?

@aslakknutsen But in [designs](https://redhat.invisionapp.com/share/KA9CAYL7M), I have not came across `all` or such tab to display all(active+inactive) iterations. So inactive `Sprint 1` will reside in past section.
ATM, list API will always return all iterations(By looking at designs pagination support is not considered yet. @sanbornsen - can you please confirm we do not paginate here ).

Concept 1 -
Dates in Iteration are for user only, system will not take any decision based on iteration dates

Concept 2 -
System will use Iteration dates only to calculate `future` or `past` category. Dates are optional till user starts iteration. If not started by user or Iteration is not having date, it will be in future section.

Main questions we should answer are -
* How `UI` will decide where to put the iteration (past/future/current) ?
* Should system disable the iteration when user `closes` it ?
* Should `core` be aware of status of Iteration (current/past/future) ?

@michaelkleinhenz @nimishamukherjee please convey your thoughts on this, we may need to take a call to finalize the strategy.

**Comment by sanbornsen** [comment]
@Essjaysee What if the user click on start and set a date in future. Shouldn't the iteration go in Future section as well?

**Comment by sanbornsen** [comment]
```iteration.isActive == nil ---> Future```
@aslakknutsen @pranavgore09 I don't feel it's correct. What if the start date is a future date, and the status is active? 
Based on what are you planning to set the value for **iteration.isActive** ?

**Comment by pranavgore09** [comment]
@sanbornsen 
If we follow this road then clicking `start` will make it active and clicking `close` will make it inactive. This is just a suggestion.
We need to finalize a [strategy](https://github.com/fabric8io/fabric8-planner/issues/647#issuecomment-272358525).

**Comment by pranavgore09** [comment]
For the scope of currnet sprint we are limiting the implementation to - 1 space 1 team 1 current iteration at a time.

Workflow-
* User can create Iteration with name(only mandatory field), description, start_date, end_date
* Newly created iteration will be seen in 'Future' category on UI.
* User can edit the iteration to change name/description/start_date/end_date
* User can start iteration by selecting start menu, validations while starting iteration are -
    1. `start_date` is greater than or equal to today
    2. No other iteration is already in Current category
* Once iteration is started, iteration will seen in 'Current' category
* User can edit the iteration to change name/description/start_date/end_date
* User can close iteration by clicking the 'Close' menu
* Once iteration is closed, iteration will seen in 'Past' category


@michaelvirgil @sanbornsen @nimishamukherjee @Essjaysee @jimmidyson @ldimaggi Please verify the workflow once.

**Comment by michaelvirgil** [comment]
@pranavgore09 When starting an iteration - the start date, I think your original statement from above is the correct one:
* start date <= current date <= end date

**Comment by pranavgore09** [comment]
@michaelvirgil  thanks, updated !

**Comment by sanbornsen** [comment]
@michaelkleinhenz how is start date < current date ?

**Comment by pranavgore09** [comment]
@sanbornsen when user wants to start the iteration with yesterday's date as start date. So user can start an iteration which starts yesterday and ends after two weeks.

**Comment by sanbornsen** [comment]
@pranavgore09 Why would the user want to start an iteration today with having an older start date?

**Comment by pranavgore09** [comment]
@sanbornsen currently our system will not automatically start the iteration, start action is manual.
If team started working for the sprint yesterday and manager starts the sprint today (which has yesterday's start_date).

**Comment by michaelvirgil** [comment]
@sanbornsen I can think of several scenarios where a user/Scrum Master or team would want to set the start date to an earlier date <= today.

If you are suggesting that the default pre-populated start date is today, that makes sense. I'm curious, you seem to imply that you would restrict the setting of the date to an earlier day - what is your thinking with this restriction? Why would you restrict this? Things change for a team... we see it all the time...

**Comment by qodfathr** [comment]
Let's get very basic functionality working now, and let's focus on that. Let's not worry about 'advanced logic' such as "does it make sense for a new iteration to have a start date to be before today?" when we do not even have the ability to create an iteration with any start date yet. Baby steps.

FWIW, yes, there are cases where a user would make an iteration with a state date < Today. There are even cases whereby a user would create an iteration with an end date < Today. (Simple example: I'm porting existing data from another system into here, but there are many others.)

**Comment by pranavgore09** [comment]
Only remaining part for this task is [PR#706](https://github.com/almighty/almighty-core/pull/706). Once merged we will be able to display `counts` in left panel of iterations.
