### ISSUE TITLE
Close an Iteration [5]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#649]
_From @michaelkleinhenz on October 27, 2016 15:16_

# Description

As a user, I want to close an iteration. Closing an iteration means the iteration has been completed.

# Functional Acceptance Criteria
1. The user can close an iteration from a dialog.
3. The iteration state is set to closed.

**Note:** work items in the state "open" (or semantically equivalent) that are contained/associated with an iteration at the time the iteration is closed are still associated with the iteration. They must be moved manually from one iteration to another. This is because in the final system, there will be a filtered global view with all work items regardless of iteration association where the user can pick and mass update work items for moving to a different (following) iteration.

**Note:** the "backlog" is considered the ordered (by order-of-execution) list of all work items of the context **not** in an iteration.

# Non-functional Acceptance Criteria
1. The "close iteration" view is easily accessible from anywhere in the system UI.

# Dependencies
1. Userstory #409 
2. Userstory #410
3. Userstory #412 

_Copied from original issue: almighty/almighty-core#411_

**Comment by michaelkleinhenz** [comment]
_From @Mgranfie on October 27, 2016 16:53_

@michaelkleinhenz and sarahjane I am wondering about the statement of closed iterations return to the backlog? I have a design for Past Iterations that will house closed iterations. Is there a call for cancelled iterations? Is this what you are referring to here to move back to the backlog?... thx.

**Comment by michaelkleinhenz** [comment]
@Mgranfie work items that are open when closing an iteration would be moved to the backlog. But that is one of the areas that are very important but also very volatile. I can think of many usable behaviours for this, even specific for a certain process. This stuff may be defined by the WILTs in the future (or some other user-configurable process) because this may be needed differently on different projects/teams/customers.

For now, we should assume something that makes sense. From the behaviour that GitHub uses, only one iteration can be set for a work item. In turn, that means we have to think about what to do with work items that are still in state "open" when an iteration is closed. In any usecase I can think of, the work items will then need to be "moved" out of the closed iteration. As we can not assume what the next iteration will be or if a work item will be in there, it's best to move them back to the backlog for new assignment to a new iteration. 

That was the reasoning about that behaviour. :-)

**Comment by michaelkleinhenz** [comment]
@qodfathr ^^

**Comment by qodfathr** [comment]
We do not need to do anything magical here. If a work item is open and assigned to a closed iteration, that's just what it is.

At some point, we'll need a way to have named queries that permit filtering of the UI, and, with that, a process template can include several helpful predefined queries which help to resolve these anomalies. e.g., there could be a query named "Prior unfinished worked" which filters the UI down to open work items assigned to prior iterations. Then the team can decide what to do with them -- e.g., maybe some of them are, in fact, done, and just need to be set to done. Maybe some need to be put 'back on the backlog'. Maybe some of them should be moved into the current or a future iteration. But let a human make the decision -- automagic generally does not help in this world.

**Comment by ldimaggi** [comment]
Can a user DELETE an iteration?

**Comment by ldimaggi** [comment]
Will we ever want to enable users to set up "auto-close" for iterations? Where an iteration will close on a predefined date? Thx!

**Comment by ldimaggi** [comment]
How can a user move work items from one iteration to another? Will they have a bulk move option?

**Comment by qodfathr** [comment]
@ldimaggi Yes, you can delete an iteration, but, in doing so, the UI has to ask for what existing iteration to use to replace all instances of the deleted iteration on WIs.

**Comment by qodfathr** [comment]
@ldimaggi "Auto close" -- sort of. When iterations have dates, the UI can determine which iteration is Current and which is Past. But the concept of 'closing' an iteration is, to me, a non-thing. It's just a concept, but it's not anything that we actually implement. There is no need to 'close' an iteration. An iteration is either Current or it is not. It's also an ordered hierarchy, so anything prior to the 'Current' iteration is past and anything after the Current iteration is future. For many, many uses cases, we do not want to over-engineer the semantics here.

**Comment by qodfathr** [comment]
@ldimaggi Yes, items can be moved between iterations. Yes, bulk move is a nice-to-have. A true bulk-update operation with a matching UX is a reasonably complex feature that should be designed to handle many different use cases (i.e. not just iterations).
Being able to multi-select WIs and drag them onto an iteration is also a nice-to-have.

**Comment by pranavgore09** [comment]
@vikram-raj : As per the description and comments above, On closing an iteration there is no effect on WI. WI in that iterations will remain as it is. And they will be moved manually.
Can you please confirm that -
1. Only "current" iteration can be closed.
2. Confirm box is shown to user after hitting "close".
3. After successfully closed, iteration is moved to "past" category.

If above things are done, then we can call this story as done.
@nimishamukherjee @michaelkleinhenz Please confirm once.

**Comment by vikram-raj** [comment]
@pranavgore09 Yes, above things are done.
