### ISSUE TITLE
View Comments on the Work Item Detail View [3]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#652]
_From @michaelkleinhenz on October 12, 2016 8:29_

**Reference:** 1603E004, 1608E138
# Description

As a user, I want to see comments on the work item detail view.
# Functional Acceptance Criteria
1. The user can view the comments as a list.
2. The comment text is interpreted as adoc markup and displayed formatted.

**Note:** no threads or hierarchies now, they will be added with a later userstory.
# Non-functional Acceptance Criteria
1. The comments are displayed in a consistent way for the UI (UX: paged, scrollview or plain).
# Dependencies
1. Userstory #298 
2. Userstory #348
3. Userstory #350
4. Userstory #351

_Copied from original issue: almighty/almighty-core#349_

**Comment by vikram-raj** [comment]
@baijum, @Mgranfie Can we have pagination in comments?

Like **Load 10 more comments**. Because suppose If we have 100 comments or more on a work item then it will take time load all at the same time.

**Comment by aslakknutsen** [comment]
@vikram-raj I believe the UX defined 'more comments' yes. Backend currently doesn't return comments paginated, but that can be done.

**Comment by Mgranfie** [comment]
This slide in the wireframe prototype, describes this behavior on number 6

https://redhat.invisionapp.com/share/6E9OIX4YB#/211288921_ALM_Commenting

**Comment by baijum** [comment]
@vikram-raj I have added a task for backend to implement the pagination #729

**Comment by baijum** [comment]
@vikram-raj pagination for backend has merged. Is there a UI task to use update UI based on this?

**Comment by baijum** [comment]
@vikram-raj I couldn't find a task for UI, so I have added it here #851
