### ISSUE TITLE
Filtered List: by Work Item Type [5]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#658]
_From @michaelkleinhenz on November 23, 2016 16:12_

# Description
As a user, I want to see a list of work items filtered by a specific work item type.

# Functional Acceptance Criteria
1. The user can navigate to a list that only contains work items with a specific type.
2. The list contains all items of the selected type regardless of other hierarchical positions of the work items.
3. Clicking on an item in the list resets the current filter (if there is any) and sets a new filter for the selected type. The new filter is also visible in the filter bar.
4. The new filter can be stacked with other filter criterias, like "assigned to me" or others using the filter bar.
4. The list behaves the same as the work item list (see [#297](https://github.com/almighty/almighty-core/issues/297)) including the reordering (see [#318](https://github.com/almighty/almighty-core/issues/318)).
5. The user can navigate to the detail view from the list and is able to navigate back, as described in [#297](https://github.com/almighty/almighty-core/issues/297).
6. The list is clearly marked/titled with the name of the selected Work Item Type.

# Non-functional Acceptance Criteria
1. The filtered list reference is implemended so that it can be navigated to by static links.

**Note:** The URL does **not** change with the filter criteria for now.

**Note:** There is no means of the user selecting a work item type for filtering within this story. This will be added in a later story. Also, it might be that there may be just static links to pre-defined work item filtered lists in the menu somewhere for now.

**Note:** it is expected that this is not a new implementation, but mere a refactoring of the existing work list view (#297), adding the filter capability.

**Note:** this story only talks about the list view, not the card view.

# Related
* Userstory [#503](https://github.com/almighty/almighty-core/issues/503) and [#504](https://github.com/almighty/almighty-core/issues/504) are closely related, difference is the filter expression.
* https://github.com/almighty/almighty-core/issues/783 [DONE]

**Comment by michaelkleinhenz** [comment]
_From @Essjaysee on December 15, 2016 20:1_

@michaelkleinhenz Just making sure I'm clear: on # 4, you mention "The user can navigate to the detail view from the list", do you mean the detail view of the epic itself or of a work item that is associated with the epic?

**Comment by debloper** [comment]
If the URL doesn't change to reflect the filtration, how does one share a filtered list (apart from screenshots), or is it out of scope for us?

**Comment by michaelkleinhenz** [comment]
So, any of the above is desirable, but for the context of this story not needed. This does not mean that we should not do it, but that we should prioritize implementation speed over functionality here. Or in other words: yes, if the above can be done so we complete the story in time, then let's do it, if not, then lets move that to later.

At least we should recognize that we need all of the above at some point and we should reflect that in the implementation.

For now, I would implement a simple filter that can be extended to an expression filter that accepts logical expressions. The URL should not be touched in the extra path, but adding get parameters to it is fine (and desired, in fact).
