### ISSUE TITLE
Enhancement request - Enable users to search for workitems

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#676]
It would be helpful for users to be able to search for workitems (based on status, type, title, description, comment) - in addition to filtering for workitems. Thx

**Comment by Mgranfie** [comment]
Yes Len, this would be great, have it on our backlog for the future, so far
this has not been something that has been needed to get to summit.

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
