### ISSUE TITLE
[BUG] - Clicking Kabob Menu Highlights Row

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#683]
When a user clicks on the kabob menu in the current UI, the row is highlighted, as if it is selected. Once highlighted, there is no way to remove the highlight without opening up an issue and then closing it. The correct method should be that the kabob menu can be opened and closed without highlighting the given row.

Kabob Open:
<img width="1915" alt="kabobopen" src="https://cloud.githubusercontent.com/assets/4032718/21849949/4f2f1d0a-d7d6-11e6-859f-76fd913a623c.png">

Kabob Closed:
<img width="1915" alt="kabobclosed" src="https://cloud.githubusercontent.com/assets/4032718/21849955/54a9f304-d7d6-11e6-937a-fb6aa4e23e96.png">

**Comment by nimishamukherjee** [comment]
@mindreeper2420 please review. Fix on http://demo.almighty.io/work-item/list

**Comment by mindreeper2420** [comment]
@nimishamukherjee Looks good.
