### ISSUE TITLE
[BUG] Checkboxes should not always be shown

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#684]
According to the design, the checkboxes for selecting a work item in the list should not be present until the row is hovered over by the user.

[Wireframe Link](https://redhat.invisionapp.com/share/HQ9ZNCXEJ#/209513812_MoveListItems_-_002)

Incorrect View:
<img width="1916" alt="checkboxes" src="https://cloud.githubusercontent.com/assets/4032718/21850288/e2c3fe9a-d7d7-11e6-95af-d66c93cd68a4.png">

**Comment by nimishamukherjee** [comment]
@mindreeper2420 on hover, after we click the check-box, the check-box remains visible irrespective of hover?

**Comment by mindreeper2420** [comment]
@nimishamukherjee that is correct - once the checkbox is checked, then it remains visible, no matter the mouse interaction/movement.
