### ISSUE TITLE
[Enhancement] Filtering UI

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#730]
Looking forward, the Filtering UI that currently exists on the demo site needs to be updated to match PatternFly's UI. As more items are added and it moves away from being a fixed, singular filter, the current method (and UI) will become obsolete.

An updated wireframe of the layout can be found on [InVision](https://redhat.invisionapp.com/share/T79EF22F9#/208756097_Fixed_Filter_-_000).

This enhancement stems from fabric8io/fabric8-ux#121

**Comment by SMahil** [comment]
it is done in two sets.
- Functional part is already merged to master. 
- UI look and feel is updated at PR #751
