### ISSUE TITLE
Seamless integration of Patternfly/js Components in UI

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#74]
We have to find a way to use the Patternfly/Bootstrap JS code in UI. Many widgets we plan to use are utilizing this code (ex. also "basic stuff" like opening/closing dropdowns). At the same time, we have to make sure the code works nicely with Angular 2 and our implementation of it.

**Comment by michaelkleinhenz** [comment]
Req: the Patternfly code should be incuded as a dependency wherever possible. Do not add Patternfly files directly to the commit unless there is no other way (there should!).

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz Patternfly has a npm package for the css version. We successfully included it in vendor.ts file and the styling worked.
Now we are using the SCSS version. Currently Patternfly does not have a npm package for the scss version and that is why we are referencing the files.
So we need to create a Patternfly SCSS npm package or wait for Patternfly :)

**Comment by michaelkleinhenz** [comment]
Mmmh. Topic for this week: both Bootstrap and Patternfly use less by default and the npm packages include the less sources. Let's discuss this week how to deal with this.

**Comment by michaelkleinhenz** [comment]
Result of discussion: we will start a port of Patternfly for Angular 2. We'll ask the Patternfly team (they are meeting next week) if they have a repository that we can contribute to. Otherwise, we're starting our own repo underneath almighty. Timeframe: End of Sprint.
