### ISSUE TITLE
WI  "title" disappears/disabled  form UI 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#740]
On Assigning WI first "title" disappears/disabled  from UI
- Create a new work time 
- Assign it to assign e , and then try to edit the Title , it does not allowed to edit title. 
Video - https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COdnRHT21qUm1sd0k/view?usp=sharing

**Comment by mindreeper2420** [comment]
@naina-verma Yes, they are the same - just different ways to break the UI :-) I'll close my duplicate.

@michaelkleinhenz I would consider this a critical bug, as it prevents the user from entering new work items.

**Comment by naina-verma** [comment]
Hi @nimishamukherjee , 
Can you please update when this bug will be fixed its been opened from long time !

**Comment by nimishamukherjee** [comment]
Fixed on planner. Need to update on platform.

**Comment by nimishamukherjee** [comment]
PR #1294 merged.

**Comment by naina-verma** [comment]
Verified !
