### ISSUE TITLE
On login WorkBoard doesn't  display 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#756]
On login WorkBoard doesn't display 
- Login, you will see only work item list 
- refresh the browser you will land to blank page , but the WorkBoard will appear on you screen
this looks like routing issue  
Video link:
https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COSUgxc0U4STVFbDQ/view?usp=sharing

**Comment by vikram-raj** [comment]
@naina-verma It is a cache issue.
