### ISSUE TITLE
Overwritten change

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#757]
Hi @sanbornsen ,

I've just discovered that you're commit 75ba0c66 has overwritten my already merged PR #744. I think it was due to renaming.

Please make sure that when you rename files (e.g. move to another location), you see it in the "git log --stat" message as a move.

Here's an example of such a message:

```
 src/tests/{app.component.spec.js => app.component.spec.js.2} | 0
 1 file changed, 0 insertions(+), 0 deletions(-)
```

To achieve that it's a good habbit to 

1. `git mv oldfile newfile`
1. commit the changes `git commit -m "Moved oldfile to newfile"`

Only then start making changes to the file; **otherwise git cannot *always* track changes and movements**. 

Please, ensure that my changes are restored and also make sure that no other changes were overwritten.

**Comment by sanbornsen** [comment]
@kwk Thanks for identifying. I didn't know about that git feature. I'll make sure your changes are back and look for other missed changes if any.

**Comment by kwk** [comment]
@sanbornsen thank you!

**Comment by nimishamukherjee** [comment]
@kwk can we close this?

**Comment by kwk** [comment]
@nimishamukherjee no, this cannot be closed because a search reveals that it is still `Assigned to Me` and not `Assigned to me`: https://github.com/fabric8io/fabric8-planner/search?utf8=%E2%9C%93&q=assigned+to+me&type=

**Comment by sanbornsen** [comment]
True, it's totally my fault. I never made the changes and lost track. We are anyway going to refactor filter bar. I'll get it fixed soon.

**Comment by sanbornsen** [comment]
Now the string is coming from backend through **/filters** api, so it's all good.
