### ISSUE TITLE
Board view in planner - does the "move" pulldown make sense?

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#777]
The options available in the move pulldown seem out of place in the board view - see screenshot. In order for these options to be usable, a user must have a means to select workitems in the board view.

![screenshot from 2017-01-18 15-02-08](https://cloud.githubusercontent.com/assets/642621/22081233/c8085588-dd90-11e6-9f96-125b40050572.png)

**Comment by Mgranfie** [comment]
@kwk @ldimaggi @michaelkleinhenz Good catch! These features were not specified as needing to show here. For a 2 pizza team we only need to consider single moves, as most sprints are smaller and more focused, ie: 2 pizza team. So no multi select is required, but the filtering can stay!

Other rules of engagement to question:

1. The position of the work item, in the backlog does not impact the position of the WI in the agile boards here, as these are based on active iterations?
2. The state of the work item should be in sync with backlog and iterations.

The filters can stay but the move more than one can be removed. LMK if this all makes sense...

**Comment by ldimaggi** [comment]
Perfect! Thx.
