### ISSUE TITLE
In the board view - creating a new workitem results in corrupted display

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#778]
See screenshot below - this display results from the user selecting to create a new workitem:

![screenshot from 2017-01-18 15-05-13](https://cloud.githubusercontent.com/assets/642621/22081273/f42e77dc-dd90-11e6-9da7-fab246f8b319.png)

**Comment by naina-verma** [comment]
@ldimaggi , I think this issue is duplicate of https://github.com/fabric8io/fabric8-planner/issues/750

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
