### ISSUE TITLE
Change "Sign in with GitHub" button to "Sign in with Red Hat Developers"

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-planner#780]
We switched to keycloak authentication instead of github in almighty-core. Our keycloak uses developers.redhat.com as Identity Provider. We now should change the label/image of the sign-in button.

**Comment by pmuir** [comment]
Can you create an issue in fabric8-ui as well please?

**Comment by alexeykazakov** [comment]
Sure - https://github.com/fabric8io/fabric8-ui/issues/75
