### ISSUE TITLE
Remove 'system.' prefix from the quick add work item form.

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-planner#783]
Refer #782. 
Quick add fails as it submits system.workitemtype. Remove 'system.' prefix from the quick add work item form.

**Comment by kwk** [comment]
@nimishamukherjee why are backend work item types encoded in the UI anyway? We should make sure that we don't have that in the UI at all, don't you think? Please, let me know if I can help with services on the backend to support this effort.

Oh, btw. I will be converting the work item type API to JSONAPI soon (https://github.com/almighty/almighty-core/issues/674).

**Comment by nimishamukherjee** [comment]
@kwk for now, I have removed the "system." prefix to enable quick add.
We can use #798 to track the discussion and implementation of dynamic setting of the quick add work item type.

**Comment by kwk** [comment]
> @kwk for now, I have removed the "system." prefix to enable quick add.
> We can use #798 to track the discussion and implementation of dynamic setting of the quick add work item type.

sounds good.

**Comment by nimishamukherjee** [comment]
PR #833 merged. Closing this issue.
