### ISSUE TITLE
Enhancement request - Auto-refresh of display of filtered workitems

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#791]
The set of workitems displayed when a filter is applied is not updated when workitems in that set are edited.  

To reproduce:

- Create multiple workitems and assign them to yourself.
- Apply the 'assign to me' filter, verify that the correct set of workitems are displayed
- Edit one or more of the workitems and change the assignee
- The full set of workitems that were originally assigned to you are still displayed

See screencast here:
https://dl.dropboxusercontent.com/u/12067552/Screencasts/no_automatic_refresh_of_filtered_data.webm

**Comment by naina-verma** [comment]
@ldimaggi  it looks similar  to : https://github.com/fabric8io/fabric8-planner/issues/608
