### ISSUE TITLE
"Date/Time" in comments should be in one line layout

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#797]
"Date/Time" in comments should be in one line layout

It looks like "PM/AM" for time is going in another line , which gives distorted view 
![screenshot from 2017-01-23 14-35-20](https://cloud.githubusercontent.com/assets/19172870/22197751/63b495f0-e179-11e6-8e9a-f542f6865b5b.png)

**Comment by SMahil** [comment]
@naina-verma Can you verify if this issue exists

**Comment by naina-verma** [comment]
@SMahil This looks fixed now !! Verified

**Comment by naina-verma** [comment]
@SMahil , It looks like something again broke this fix 

![screenshot from 2017-02-03 10-27-11](https://cloud.githubusercontent.com/assets/19172870/22580086/79c5f7b4-e9fb-11e6-9486-ec8626d26dce.png)

**Comment by naina-verma** [comment]
@SMahil , It happend on specific  Version 54.0.2840.59 (64-bit) chome , closing issue for now !
