### ISSUE TITLE
The work item link type search box needs to be cleared when switching between tabs.

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-planner#800]
@naina-verma creating this issue for the tab's fix:

Please look into video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COc2Y4SDZ1RUwzVms/view?usp=sharing
Its partially fixed . In video you will see that one changing tabs with invalid wi-id , its not clearing the fields.

**Comment by naina-verma** [comment]
@nimishamukherjee , yes its partially fixed . you can track this in new issue also .
