### ISSUE TITLE
Test enhancement - divide functional (UI) tests into suites

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#806]
The UI functional tests (tests invoked by run_functional_tests.sh) have grown to the point that they now require 4-5 minutes to run. We would like to divide the tests into suites so that that we can create many more new tests (including negative tests), where not all new tests will be run for every new PR.

**Comment by kwk** [comment]
Maybe we can put together a [smoke test](https://en.wikipedia.org/wiki/Smoke_testing_(software)) suite that runs the most important test cases?

**Comment by ldimaggi** [comment]
YES - that is the plan!

**Comment by michaelkleinhenz** [comment]
Yes, makes sense.

**Comment by ldimaggi** [comment]
See PR:
https://github.com/fabric8io/fabric8-planner/pull/916

**Comment by ldimaggi** [comment]
Closing this - we'll address this when the tests are refactored.
