### ISSUE TITLE
Iteration and workItem detail overlapped ,Distorted display 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#810]
Iteration and workItem detail overlapped ,Distorted display 
![screenshot from 2017-01-24 11-33-37](https://cloud.githubusercontent.com/assets/19172870/22236042/197d6934-e229-11e6-936a-91b5a0cfc8d8.png)

**Comment by mindreeper2420** [comment]
@vikram-raj @naina-verma why is UX needed for this? This is a z-index bug. Looking at the code, the panel is set to a crazy high 9999.
