### ISSUE TITLE
Iteration "Name" with large string breaks layout on left side display 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#831]
Iteration "Name" with large string breaks layout in sidebar display 
It should be show limit number of characters ending with (...) to specify continue . 

![screenshot from 2017-01-30 10-03-56](https://cloud.githubusercontent.com/assets/19172870/22412350/940d1178-e6d3-11e6-86e5-330863552285.png)

**Comment by Essjaysee** [comment]
And it should include a hover/tooltip that lets the user view the full iteration name.  See http://www.patternfly.org/pattern-library/widgets/#tooltip
