### ISSUE TITLE
Support for markdown in work item descriptions

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-planner#835]
Now that https://github.com/almighty/almighty-core/pull/636 has been fixed and merged, the UI should benefit from the support for Markdown in work item descriptions.

Support for Markdown markup language requires work on both requests and responses.

### Changes in request format:

In order to support Markdown input between the UI and the platform,  the format of work item creation and update requests should be changed to the following form:

````
...
{ "system.description": 
  { "content": "some markdown content",
    "markup": "Markdown"
  }
}
...
````

The server accepts both this new request format, as well as the current (legacy) format, in which case the markup language associated with the work item description is assumed to be `PlainText`

### Changes in response processing:

The server already returns a couple of sibling elements to the current `system.description` attribute:
- `system.description.markup`: contains the type of markup language associated with the returned `system.description` attribute. It can be `PlainText` or `Markdown`
- `system.description.rendered`: contains the rendered fragment of HTML corresponding to the 'raw' `system.description` attribute. 

`system.description.rendered` should be used to display the description in 'view' mode, and `system.description` should be used to display the description in `edit` mode.

**Comment by mindreeper2420** [comment]
@sanbornsen here is the UX for showing that an input accepts Markdown: [Wireframe for Markdown Support](https://redhat.invisionapp.com/share/GRAHX5HSQ#/219093352_Detail_Panel-Edit).

The Markdown icon can be found here: https://github.com/dcurtis/markdown-mark. It is not part of either PatternFly icons or Font Awesome, so the icon will need to be downloaded.

**Comment by sanbornsen** [comment]
@mindreeper2420 Thanks for the wireframe. We need a view toggle so that the user can switch from Markdown view to HTML view for a preview. What do you think?

**Comment by mindreeper2420** [comment]
@sanbornsen I can add that, but the initial conditions did not include any kind of preview - just the ability to write in Markdown, if desired.

@joshuawilson @michaelkleinhenz is this part of the comment that Aslak made regarding the color-coding of the language types? Would that be part of the preview capabilities?

**Comment by sanbornsen** [comment]
@alexeykazakov @aslakknutsen 
I am getting the same markdown format in rendered as well. Can you guys look into it?
Example : 
system.created_at: "2017-02-10T07:07:31.648352Z"
system.description: "## So this is it↵↵* Hello↵* HEY↵↵## HEADER 2↵* This is great↵* This is list item 2↵↵### New Header"
system.description.markup: "PlainText"
system.description.rendered: "## So this is it↵↵* Hello↵* HEY↵↵## HEADER 2↵* This is great↵* This is list item 2↵↵### New Header"
system.remote_item_id: null
system.state: "new"
system.title: "New item 6"
version: 17

**Comment by alexeykazakov** [comment]
@xcoulon please take a look ^

**Comment by aslakknutsen** [comment]
@xcoulon This is broken as far as I can tell. Create/Update assumes system.description should be parsed to type ```target.Fields[workitem.SystemDescription].(rendering.MarkupContent)```, but when called via HTTP and deserializing this comes out as a Map[string]interface{}.

**Comment by aslakknutsen** [comment]
Ops, referenced the wrong issue in the commit: https://github.com/almighty/almighty-core/commit/ca531794864dbaedebe52936efa7409ac1adb112
