### ISSUE TITLE
"add a workitem" icon looks very small 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#836]
"add a workitem" icon looks very small on screen 
![screenshot from 2017-01-30 16-24-50](https://cloud.githubusercontent.com/assets/19172870/22420514/b482d4c6-e708-11e6-9f2d-a02b1cc383cd.png)

**Comment by Ritsyy** [comment]
@naina-verma  UX design for the icon https://redhat.invisionapp.com/share/HJ9YNYX2T#/screens/213678972

**Comment by naina-verma** [comment]
@Ritsyy Thanks for link.

But, if you look into screenshot and match invision (+) is not aligned properly . "Plus" is not in center if circle and boarder looks bold .
