### ISSUE TITLE
WI creation: Cannot go back to title input field after leaving it empty and switching to description input field

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#842]
1. Open the work item creation dialog and start typing something into the title field. Then remove all the text. (Alternatively, you can leave it empty altogether.)
2. Change to the description input field.
3. Notice, that you cannot go back to the title input field. (Not even with <Shift>+<Tab>)

See this screen capture for an example

![optimised](https://cloud.githubusercontent.com/assets/193408/22431202/ff5fe0bc-e710-11e6-8310-c66f364293e7.gif)

**Comment by naina-verma** [comment]
@kwk , looks similar to :https://github.com/fabric8io/fabric8-planner/issues/740

**Comment by kwk** [comment]
@naina-verma Yes. This is a duplicate of #740 . Sorry for having searched the already opened issues.
