### ISSUE TITLE
Iterations with Past dates should not create

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#847]
Iterations with Past dates should not be created 
![screenshot from 2017-01-31 14-06-41](https://cloud.githubusercontent.com/assets/19172870/22457660/a7ef647a-e7be-11e6-8e1f-f0b91e31a0c4.png)

**Comment by pranavgore09** [comment]
@naina-verma Please take a look at this comment https://github.com/fabric8io/fabric8-planner/issues/647#issuecomment-272883624

**Comment by aslakknutsen** [comment]
Past start date is a valid user case
