### ISSUE TITLE
No error/ warning shows when one Itreation is running and try to start another iteration

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#859]
No error/ warning shows when one Itreation is running and try to start another iteration 
API works fine for this , UI needs to show the Warning on screen
Video : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6CObW5RVmdEUHVBQlk/view?usp=sharing

**Comment by vikram-raj** [comment]
This issue is same as #839
