### ISSUE TITLE
"Current Iteration" updated with Future date ?

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-planner#860]
Current Iteration updated with Future date ?

Steps to reproduce : 
- Moved one iteration from future to current , it automatically set up its date to today and end day after a week
- Edit the Current sprint date to Future date as 2 weeks later , it git updated 
Is it a valid behavior @fabric8io/uxd  ?

![screenshot from 2017-02-01 11-23-51](https://cloud.githubusercontent.com/assets/19172870/22496591/04bdff74-e871-11e6-98bc-f110e66c709d.png)

**Comment by Essjaysee** [comment]
Once an iteration is started (thus making it current), the only date that should be changeable is the end date.
