### ISSUE TITLE
UI distorts at Iteration Panel when Iteration header is too long

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#864]
UI distorts at Iteration Panel when Iteration header is too long.

<img width="382" alt="screen shot 2017-02-01 at 3 15 21 pm" src="https://cloud.githubusercontent.com/assets/10396359/22502056/5cf47f18-e891-11e6-94ba-bbfd3155195a.png">

**Comment by vikram-raj** [comment]
Similar to #831

**Comment by vikram-raj** [comment]
This issue is fixed and merged #831.
