### ISSUE TITLE
WIP Brainstorming on link types to show in the create link dialog

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#865]
# Purpose

Creating links using the correct link types.

# Context
Given this chain of work item that are linked together

    epic -> userstory -> task

these **fictional** link types are involved:

| name | source WIT | target WIT | forward name | reverse name |
|------|------------|------------|--------------|--------------|
| epic-to-userstory | epic | userstory | parent of | child of |
| userstory-to-task | userstory | task | parent of | child of |
| planneritem-to-planneritem | planneritem | planneritem | relates to | is related to |

From this point onward, think as if you were looking at the work item details dialog for the **userstory** work item. And now suppose you want to create a link.

## What are the source link types?

Source link types are all those link types in which the current userstory work item can be placed in the source part of the link:

| name | source WIT | target WIT | forward name | reverse name |
|------|------------|------------|--------------|--------------|
| userstory-to-task | userstory | task | parent of | child of |
| planneritem-to-planneritem | planneritem | planneritem | relates to | is related to |

## What are the target link types?

Target link types are all those link types in which the current userstory work item can be placed in the target part of the link:

| name | source WIT | target WIT | forward name | reverse name |
|------|------------|------------|--------------|--------------|
| epic-to-userstory | epic | userstory | parent of | child of |
| planneritem-to-planneritem | planneritem | planneritem | relates to | is related to |

## How to get the source and target link types? 

Since this commit (https://github.com/almighty/almighty-core/commit/d46f3c2ea7bd240775b3c82ba36b49eafc4b891e) you can find out about those link types by querying the URL that is provided in a work item's JSONAPI response when you go to one of these JSON elements:

* `data.links.sourceLinkTypes`
* `data.links.targetLinkTypes`

See this example response for a work item:

```json
{
   "data" : {
      "relationships" : {
         // [Removed for clarity]
      },
      "type" : "workitems",
      "attributes" : {
         // [Removed for clarity]
      },
      "links" : {
         "self" : "http://localhost:8080/api/workitems/1",
         "sourceLinkTypes" : "http://localhost:8080/api/workitemtypes/feature/source-link-types",
         "targetLinkTypes" : "http://localhost:8080/api/workitemtypes/feature/target-link-types"
      },
      "id" : "1"
   }
}
```

Here's a real world example: http://demo.api.almighty.io/api/workitems?page[limit]=23

# What to display in the link type drop-down box?

As you might have noticed, the work item link type "planneritem-to-planneritem" appears in the source and in the target link types. One must be ignored.

So far our list of link types to choose from when creating a link should be:

* relates to
* is related to

As you might have noticed the forward and reverse names in the other two link types are exactly the same:

* parent of
* child of
* parent of
* child of

For a user this makes it impossible to distinguish what is meant by those link types.

## Solution

1. For source link types we only display the forward name.
1. For target link types we only display the reverse name.
1. For duplicate link types like "planneritem-to-planneritem" we do the same.

This would leave us with this list of types:

* parent of
* child of
* relates to
* is related to

(kudos to @nimishamukherjee for this idea)

**Comment by sanbornsen** [comment]
From the link, http://demo.api.almighty.io/api/workitemtypes/planneritem/source-link-types it's clear that the source or destination link type is not based on the current work item but it's based on the current work item type. Why fetching this data for every work item through the link instead of as a relationship with work item type?

**Comment by kwk** [comment]
@sanbornsen 

> Why fetching this data for every work item through the link instead of as a relationship with work item type?

As you might know, the type is currently not available via JSONAPI but I'm working on it (see https://github.com/almighty/almighty-core/issues/674). As soon as we have it we can adjust and migrate the link over to a relationship on the WIT.

**Comment by aslakknutsen** [comment]
@sanbornsen The context you're in is a WorkItem. And you're not fetching it for each WorkItem, just that each WorkItem reference it. Normal cache rules from the server will take care of the 'fetch multiple times' issue.

**Comment by kwk** [comment]
The outcome of a meeting with @sanbornsen and @aslakknutsen today was that we begin implementing the proposed solution from this issues description.

**Comment by sanbornsen** [comment]
@kwk are we good on this? Can we close the issue?

**Comment by kwk** [comment]
@sanbornsen yes, this can be closed.
