### ISSUE TITLE
[QUESTION] Two of me in the system?

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#877]
When I go to assign a user to a Work Item, I am presented with the list that has my name twice, but with different icons. Both are my profile icons (one for GitHub, the other for the Red Hat Developer site).

Should this be occurring?

<img width="384" alt="screen shot 2017-02-02 at 2 14 45 pm" src="https://cloud.githubusercontent.com/assets/4032718/22550800/28db7ef4-e952-11e6-8f0b-1905e7d7277f.png">

**Comment by aslakknutsen** [comment]
Not really. It's a temp glitch due to the change of auth provider. It'll be
gone when we move to a new clean DB on the integration cluster.
