### ISSUE TITLE
Display Work Item Types Filter Selection in Sidebar Menu [5]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#882]
# Description
As a user, I want to quickly navigate to filtered work item types lists.

# Functional Acceptance Criteria
1. The user can navigate to a list that only contains work items with a specific type (see #658) using a sidebar menu.
2. The sidebar menu contains a hardcoded list of links.
5. Labels and Title of the sidebar menu is subject to UX definition.

# Non-functional Acceptance Criteria
None.

**Note:** The sidebar menu is hardcoded for the context of this story, but will be dynamically created later by retrieveing a category of work item types from the backend.

# Related
* Userstory #658.

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz we need:

- UX for list links on the side panel
- list of links to be hard coded

Would there be hierarchy within these list of links?
