### ISSUE TITLE
Changing Work Item States in Card View [5]

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#886]
# Description
As a user, I want to change the state of a Work Item by drag-and-dropping it in the Card View.

# Functional Acceptance Criteria
1. The Card View has a lane for each possible state the currently displayed Work Item type can be in.
2. The user can change the state of a Work Item displayed as a card by drag-and-drop moving it to another lane.
3. The user can, at the same time, change the order of execution by inserting at a selected vertical position in the selected lane.

# Non-functional Acceptance Criteria
1. All changes are done in-place.

**Note:** As this story represents a combined operation description (drop can change state and order-of-execution), the implementation of this story and the peer story should be considering each other.

# Related
1. Userstory #887.

**Comment by mindreeper2420** [comment]
@vikram-raj I'll be the UX point person on this Issue, if you'd like to go over the wireframes or if you have any questions/comments/concerns. My schedule and times are flexible, so just let me know when you'd like to take a few minutes :-)

**Comment by vikram-raj** [comment]
@mindreeper2420 Can you please put the wireframe link here?

**Comment by mindreeper2420** [comment]
@vikram-raj Here is the wireframe of the interactions and animations: [Board View w/WI Item Details](https://redhat.invisionapp.com/share/XD9ZNX7M7#/210499779_Boardview-All). This covers the method for changing in the Work Item Detail Panel (which is the same as the List View model) and the interactions for dragging cards from column to column. The process for changing the Status and what occurs to the Work Items (if they sync between Board and List View, etc.) is being handled by @catrobson

**Comment by mindreeper2420** [comment]
Hi @vikram-raj - please contact @catrobson regarding the follow-up process for this. She'll be working on this going forward :-)

**Comment by vikram-raj** [comment]
Hi @mindreeper2420 and @catrobson, Thanks for the wireframe link I will start working on that.

**Comment by catrobson** [comment]
@vikram - great.  Reach out if you have any questions!  Do you want me to set something up for us to check in later this week or next week?

**Comment by vikram-raj** [comment]
Hi @catrobson, [Here](https://youtu.be/MiEuj0fIzDM) is the video of drag and drop implementation in board view.

**Comment by catrobson** [comment]
@vikram-raj - thanks!  From an interaction design standpoint the implementation looks great.  I believe we still have to finalize visual design and we'll pass along any modification necessary for visual design in the upcoming weeks.  You can follow that story here:  https://github.com/fabric8io/fabric8-ux/issues/136
