### ISSUE TITLE
Bug: Update UI for filter result bar as per Patternfly

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#895]
The Filter results bar does not match the designs as per Patternfly

Fonts are big
Border Top has to come for bar
Label Background is different

<img width="1436" alt="screen shot 2017-02-06 at 1 00 42 pm" src="https://cloud.githubusercontent.com/assets/10396359/22638217/bc58e3de-ec6c-11e6-8626-075f8a815a8a.png">

Patternfly Visuals are:

![Uploading Screen Shot 2017-02-06 at 1.05.11 PM.png…]()

**Comment by nimishamukherjee** [comment]
@SMahil the PatternFly screenshot does not load.
