### ISSUE TITLE
[BUG] Cannot Add Title After Clicking Away

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-planner#905]
When creating a new Work Item using the full-form method (in the Detail Panel), I am unable to return to the Title field after leaving the input box. At this point, the user is unable to save their new Work Item.

Steps to Reproduce:
1. Click on the '+' to bring up the full-form Create Work Item options
2. Select a Work Item type (any will do)
    - Title field is autofocused
3. Leave the Title field by clicking into the Description field.
4. Close the Description field
5. Title field can no longer be interacted with - breaking bug

<img width="945" alt="screen shot 2017-02-06 at 3 14 51 pm" src="https://cloud.githubusercontent.com/assets/4032718/22664522/09061cf8-ec7f-11e6-862f-e83d644de847.png">

**Comment by naina-verma** [comment]
Looks similar to : https://github.com/fabric8io/fabric8-planner/issues/740

**Comment by mindreeper2420** [comment]
Closing as it is a duplicate of #740.
