### ISSUE TITLE
Check npm dependencies for build warnings

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-planner#91]
Currently, the build outputs some warnings that should be examined:

npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!  
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue  
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.  
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade  
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by ppitonak** [comment]
Jade is tricky one because they haven't had final 2.x release yet.

**Comment by joshuawilson** [comment]
@michaelkleinhenz can you please check this and post any warnings you are still getting. I have cleared a lot of them.

**Comment by joshuawilson** [comment]
@michaelkleinhenz can you please confirm?

**Comment by michaelkleinhenz** [comment]
I still get some warnings:
```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```
last two are new. I don't know how severe that is. Maybe these are just integration warnings between 3rd party dependencies.

I also get a warning in the prostinstall of Patternfly:
```
> patternfly-bootstrap-treeview@1.0.0 install /home/kleinhenz/RedHat/almighty-ui/node_modules/patternfly/node_modules/patternfly-bootstrap-treeview
> bower install

sh: bower: Command not found.
```
Looks like a missing dependency of bower in Patternfly's package.json. They might consider bower a global prerequisite.

Also, at the end of the build there are some warning from codelyzer:
```
npm WARN codelyzer@1.0.0-beta.2 requires a peer of @angular/compiler@~2.1.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.2 requires a peer of @angular/core@~2.1.0 but none was installed.
```
These should be low impact, though.

**Comment by ppitonak** [comment]
1. `cross-spawn-async` comes with `ghooks` which seems not to be used in project (see https://github.com/almighty/almighty-ui/issues/145), there is new version of ghooks so upgrade might help
2. `lodash-node` comes with `karma-htmlfile-reporter`, upgrade to latest version helps
3. problem with `patternfly-bootstrap-treeview` is fixed in newer versions of `patternfly`
4. warnings by `codelyzer` should disappear when we upgrade to Angular 2.1 (https://github.com/almighty/almighty-ui/issues/175)
