### ISSUE TITLE
WI title text overflow from input box on detail page.

### ISSUE THREAD

**Issue by vikram-raj** [fabric8io/fabric8-planner#915]
Screenshot for reference

![screenshot from 2017-02-08 00-49-57](https://cloud.githubusercontent.com/assets/2561818/22707364/916eedb2-ed98-11e6-8024-10ae8f345709.png)

**Comment by Mgranfie** [comment]
Hi Vikram..

Is this a bug or do you need some UX solutions to handle these use cases?...

-Monica

**Comment by vikram-raj** [comment]
Hi @Mgranfie,

It's a bug, input field should expand when a user enters long title. Correct me if I am wrong.
