### ISSUE TITLE
Implement UI tests for user login (token) timeout

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#947]
The access token should expire after the user logout by itself. What happens in the system at the moment is that the token expires exactly after the user log out from the system.

Steps to test:
1. Generate a token
2. Keep playing with the system for some time.
3. Logout from the app.
3. Your token becomes invalid and you need to re-authenticate

Acceptance criteria:

    Access token only expires when I manually destroy it (log out).

**Comment by naina-verma** [comment]
https://github.com/almighty/almighty-core/issues/774 Issue related !

**Comment by alexeykazakov** [comment]
Note that https://github.com/almighty/almighty-core/issues/774 is the backend part (almighty-core) only.
@dgutride is working on the UI part - https://github.com/fabric8io/fabric8-ui/issues/157

**Comment by ldimaggi** [comment]
No longer needed.
