### ISSUE TITLE
Available Filters

### ISSUE THREAD

**Issue by Ritsyy** [fabric8io/fabric8-planner#948]
There should be an API to show all the available filters.
Right now they are hardcoded in the UI.

GET /api/availablefilters

Response
```
{
   "data": [
    {
      "attributes": {
              "filter_key": "filter[assignee]",
              "filter_name": "Assignee"
      },
   "id": "84cec251-08b5-422c-ae80-3f10872ba15c",
   "links": {
         "self": "http://demo.api.almighty.io/api/availablefilters/84cec251-08b5-422c-ae80-3f10872ba15c"
    },
 },
 {
      "attributes": {
              "filter_key": "filter[area]",
              "filter_name": "Area"
      },
   "id": "bee8ec1c-094d-4fdd-afdd-00063d958702",
   "links": {
         "self": "http://demo.api.almighty.io/api/availablefilters/bee8ec1c-094d-4fdd-afdd-00063d958702"
    },
 }
 ]
}
```

**Comment by Ritsyy** [comment]
@aslakknutsen @kwk @michaelkleinhenz Can we keep the available filters in backend rather than hard coding all of them in the UI?

**Comment by aslakknutsen** [comment]
@Ritsyy yes, good idea. I think all the different WorkItemLists should contain a link to available filters. A hardcoded list returned at something like /api/filters is a good start. Then we can start adding specialized filter links to special WorkItemLists as we see fit in the future.

**Comment by aslakknutsen** [comment]
On top of my head something like:

```json
{
	"data": [
		{
			"attributes": {
				"title": "Area",
				"description": "Filter by area"
				"query": "filter[areas]={id}",
				"type": "areas",
			},
			"attributes": {
				"title": "Assignee",
				"description": "Filter by assignee"
				"query": "filter[assignee]={id}",
				"type": "users",
			}
		}
	]
}
```

**Comment by sbose78** [comment]
Could we use HTTP OPTIONS [1] for this on /api/workitems  and have the information in the body ?


[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

**Comment by aslakknutsen** [comment]
@sbose78 Unsure, would need more research. OPTION has some special usage around CORS etc and is generally considered uncacheable. A GET on the same resource with an alternative MediaType is another option. Or a simple link in the response that points to some form of resource doc.

**Comment by Ritsyy** [comment]
@aslakknutsen Yes, id will also be needed, right?

**Comment by aslakknutsen** [comment]
@Ritsyy We don't need to store them in the database at this point. Not sure what use the ID on them would be?

**Comment by Ritsyy** [comment]
@aslakknutsen yes we are not storing it in a database, but a normal id like we have for workitems?
I am not sure about it actually, just asking?

**Comment by Ritsyy** [comment]
@aslakknutsen I have started working on the above idea of hardcoding the filters currently. I'll be having a PR shortly for this. Thanks for the suggestion :)
