### ISSUE TITLE
Update the number of comment limit

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#959]
As per the UX provided we have limit of 5 for comments.

Visuals are:  
https://redhat.invisionapp.com/share/6E9OIX4YB#/screens/211288921_ALM_Commenting

**Comment by baijum** [comment]
@SMahil This works now like this (backend need not be changed).
```
http://demo.api.almighty.io/api/workitems/49/comments?page[offset]=0&page[limit]=5
```
@aslakknutsen Do we need to change the default limit for comments in the backend?

**Comment by aslakknutsen** [comment]
@baijum We don't have to, we could.

**Comment by baijum** [comment]
I am closing this as the API is not going to be changed.
