### ISSUE TITLE
Add Iteration Header in Sidebar and add Collapse to it

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-planner#965]
On Click on Iteration Header , user can toggle the accordion

https://redhat.invisionapp.com/share/YVA4PGYA3#/screens/218856936

**Comment by joshuawilson** [comment]
I didn't see where the Iteration toggle in there so I can't verify the UX.

However in the implementation you only hide the contents not the section. There is still the box the help the Iterations and the Add Iteration at the bottom. I would think an accordian would role it all up.

@fabric8io/uxd can you please confirm?

**Comment by mindreeper2420** [comment]
@joshuawilson @SMahil this is not the correct wireframe - the wireframe linked is for the tree hierarchy. There currently is no design for toggling the Sidebar.

The plus next to Iteration refers to this design for adding an Iteration: https://redhat.invisionapp.com/share/WSAJ8VUD3#/210388737_Associate_Iteration_On_WI_Detail
