### ISSUE TITLE
UI test mocking code fails when creating a new iteration or editing an existing iteration

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-planner#970]
Seeing 2 separate issues:

- Duplicate iterations entries are created when a new iteration is created. These duplicates are added to both the UI display and the iterations array in the mocking code.
- Iterations are removed from the UI when they are edited. The edited iterations (correctly) remain in the iterations array in the mocking code.

**Comment by naina-verma** [comment]
@ldimaggi , Fixed in https://github.com/naina-verma/fabric8-planner/tree/crud_iteration_test , please take a look!

**Comment by ldimaggi** [comment]
Closing as out of date - no longer an issue.
