### ISSUE TITLE
API to get work item children

### ISSUE THREAD

**Issue by baijum** [fabric8io/fabric8-planner#980]
This API gives direct descendant of work items

```
GET /api/workitems/{id}/children
```

The work item relationships will get one more entry like this:
```
...
"relationships": {
  ...
  "children": {
    "links": {
      "related": ".../api/workitems/{id}/children"
    },
    "meta": {
      "totalCount": 2
    }
  },
...
```
The API to get work items also should be modified to get the **count of children** for each work item.

Story: #884

**Comment by sbose78** [comment]
There could be 2 ways to do it :

1. Not have a new endpoint and use the existing endpoint and have the 'child' workitem embedded in the workitem relationship block. This will allow the UI to display the child workitem on the workitem list page without making any further server requests. But this is going to not as easy as (2). So let's go for (2) now. Discussed with @sanbornsen and @nimishamukherjee  :)

2. Have the new endpoint in the `relationships` part of the response for the UI to pickup and fire a request to the server for fetching the children , needed to render in the UI.

Let's go with approach (2).

**Comment by baijum** [comment]
I am planning to move **count of children** to a separate issue and PR.

**Comment by baijum** [comment]
I have added an issue to track the count of children: #984
