### ISSUE TITLE
There is no scroll for iterations on the side panel

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-planner#987]
There is no scroll for iterations on the side panel

**Comment by mindreeper2420** [comment]
@nimishamukherjee - is there a UX design that you are referencing for this? The commit around this appears to differ from UX thinking around scrolling in the Planner.

**Comment by Mgranfie** [comment]
Sj is currently working on the scroll and resize behaviors for the planner
screens. Sj can you connect with Nimisha on this?

**Comment by mindreeper2420** [comment]
@essjaysee - see above ^^^

**Comment by Essjaysee** [comment]
Hi @nimishamukherjee, here are the wireframes: https://redhat.invisionapp.com/share/QMAK3BLYP

**Comment by nimishamukherjee** [comment]
Thanks @Essjaysee @mindreeper2420 @Mgranfie .
Will update accordingly.
