### ISSUE TITLE
Empty comments -> No validation for "ENTER" keypress

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#992]
Huge empty comment space

![screenshot from 2017-02-22 10-41-31](https://cloud.githubusercontent.com/assets/6303309/23198299/94115276-f8ec-11e6-970d-cd5fa8ce82f3.png)
![screenshot from 2017-02-22 10-41-47](https://cloud.githubusercontent.com/assets/6303309/23198300/9691864c-f8ec-11e6-899b-82cdcf302e86.png)

**Comment by debloper** [comment]
How to reproduce?

**Comment by DhritiShikhar** [comment]
@debloper 
[1] Add a comment with some characters
[2] Erase the comments by pressing Backspace
[3] Press enter

You will get a huge empty comment space.
