### ISSUE TITLE
Use titles, descriptions, icons (CSS class names) defined in WIT

### ISSUE THREAD

**Issue by kwk** [fabric8io/fabric8-planner#997]
Child of #883 
(See mail entitled “Process Template - icons for status & WI types” in devtools-almighty ML)

**Comment by kwk** [comment]
The work item details view [now](643b2fec81b190a984b7502efce81efdeec677cf) uses some labels ("Assignees", "Creator", "Iteration") as defined in the work item type.

**Comment by kwk** [comment]
The work item type names, icons and descriptions are now (6ee510e4b600abaf06cbb25e9428508cad041a9e) also fetched directly from the work item type:

**Comment by kwk** [comment]
@michaelkleinhenz is there anything missing?

**Comment by michaelkleinhenz** [comment]
Done.
